<?php
use VazinCMS\Security;
$identityTheme=is_array($currentUser)&&in_array(($currentUser['identity_theme']??null),['system','light','dark'],true)?(string)$currentUser['identity_theme']:'system';
$identityName=is_array($currentUser)?trim((string)($currentUser['identity_display_name']??'')):'';
$displayName=$identityName!==''?$identityName:(is_array($currentUser)?(string)($currentUser['name']??''):'');
$identityPicture=is_array($currentUser)?(string)($currentUser['identity_picture_url']??''):'';
$moduleNavigation=$currentUser?\VazinCMS\ExtensionManager::adminNavigation():[];
?>
<!doctype html><html lang="<?=Security::e(\VazinCMS\UiLocale::locale())?>" dir="<?=\VazinCMS\UiLocale::direction()?>" data-theme="<?=Security::e($identityTheme)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title><?=Security::e(($title??'مدیریت').' · '.$customerBrand)?></title><script nonce="<?=Security::e(Security::cspNonce())?>">try{const t=localStorage.getItem('site-admin-theme');if(['light','dark','system'].includes(t))document.documentElement.dataset.theme=t}catch(e){}</script><link rel="preload" href="/assets/Vazirmatn.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/app.css"><link rel="stylesheet" href="/assets/app-14.css?v=<?=rawurlencode($appVersion)?>"><link rel="stylesheet" href="/assets/app-30.css"><link rel="stylesheet" href="/assets/auth-fix-521.css?v=5.2.1"><link rel="stylesheet" href="/assets/admin-53.css?v=5.3.0"><link rel="stylesheet" href="/assets/admin-60.css?v=6.0.0"><link rel="stylesheet" href="/assets/theme-70.css?v=<?=rawurlencode($appVersion)?>"><link rel="stylesheet" href="/assets/visa-cases-1050.css?v=<?=rawurlencode($appVersion)?>"><link rel="stylesheet" href="/assets/identity-profile-1061.css?v=<?=rawurlencode($appVersion)?>"><link rel="stylesheet" href="/assets/platform-1010.css?v=<?=rawurlencode($appVersion)?>"></head><body>
<?php if($currentUser):?><header class="admin-header"><div class="header-inner"><a class="brand" href="/admin"><span><?=Security::e($customerBrand)?></span></a><button class="menu-toggle" type="button" aria-controls="admin-navigation" aria-expanded="false">منو</button><nav class="admin-nav" id="admin-navigation"><a href="/admin/pages">صفحه‌ها</a><?php if(($openAdvisoryCount??0)>0):?><a href="/admin/seo" class="status warning">⚠ <?=(int)$openAdvisoryCount?> اخطار</a><?php endif;?><?php foreach($moduleNavigation as $item):?><a href="<?=Security::e($item['path'])?>"><?=Security::e(\VazinCMS\UiLocale::t($item['label']))?></a><?php endforeach;?><a href="/admin/media">رسانه</a><a href="/admin/menus">منوها</a><a href="/admin/revisions">نسخه‌ها</a><a href="/admin/settings">تنظیمات</a><a href="/admin/extensions">قالب‌ها و ماژول‌ها</a><a href="/" target="_blank" rel="noopener">مشاهده سایت</a><form class="logout-form" method="post" action="/auth/vazin-id/start"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="return_to" value="/admin"><button class="logout-link">اتصال Vazin ID</button></form><button class="theme-toggle" type="button" data-theme-toggle aria-label="تغییر ظاهر">◐ <span>ظاهر</span></button><?php if($displayName!==''):?><span class="identity-profile"><?php if($identityPicture!==''):?><img src="<?=Security::e($identityPicture)?>" alt="" width="32" height="32" loading="lazy" decoding="async" referrerpolicy="no-referrer"><?php endif;?><span><strong><?=Security::e($displayName)?></strong><?php if(($currentUser['identity_username']??'')!==''):?><small>@<?=Security::e((string)$currentUser['identity_username'])?></small><?php endif;?></span></span><?php endif;?><form class="logout-form" method="post" action="/logout"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><button class="logout-link">خروج</button></form></nav></div></header><?php endif;?><main>
