<?php
declare(strict_types=1);
$root = dirname(__DIR__); $db = sys_get_temp_dir() . '/vazin-online-' . bin2hex(random_bytes(6)) . '.sqlite';
putenv('DB_CONNECTION=sqlite'); putenv('DB_DATABASE=' . $db); putenv('SESSION_SECURE=false');
putenv('EXTERNAL_DELIVERY_ENABLED=true'); putenv('TELEGRAM_NETWORK_ENABLED=false');
require $root . '/src/bootstrap.php';
$pdo = VazinCMS\Database::connection(); $pdo->exec((string)file_get_contents($root . '/database/schema-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.2.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.3.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.4.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.5.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.6.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.7.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.8.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/0.9.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/1.0.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/1.1.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/1.2.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/1.3.0-sqlite.sql'));
$pdo->exec((string)file_get_contents($root . '/database/migrations/1.5.0-sqlite.sql'));
$pdo->exec("INSERT INTO users(name,email,password_hash,role,status) VALUES('Owner','owner@example.test','hash','owner','active')");
$pdo->exec("INSERT INTO products(slug,name,type,status,current_version) VALUES('vazincms','VazinCMS','cms','detached','6.0.2')");
assert((int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='owner'")->fetchColumn() === 1);
assert((string)$pdo->query("SELECT status FROM products WHERE slug='vazincms'")->fetchColumn() === 'detached');
$pdo->exec("INSERT INTO orders(order_number,user_id,product_id,product_name,amount,currency,status) VALUES('VO-TEST-001',1,1,'VazinCMS',100,'RUB','completed')");
$pdo->exec("INSERT INTO services(user_id,product_id,order_id,name,status) VALUES(1,1,1,'VazinCMS','active')");
assert((int)$pdo->query("SELECT COUNT(*) FROM services WHERE status='active'")->fetchColumn() === 1);
$pdo->exec("INSERT INTO invoices(invoice_number,order_id,user_id,subtotal,total,currency,status) VALUES('INV-TEST-001',1,1,100,100,'RUB','unpaid')");
$pdo->exec("INSERT INTO payments(invoice_id,user_id,amount,currency,method,status) VALUES(1,1,100,'RUB','manual','confirmed')");
$pdo->exec("UPDATE invoices SET status='paid' WHERE id=1");
assert((string)$pdo->query("SELECT status FROM invoices WHERE id=1")->fetchColumn() === 'paid');
$pdo->exec("INSERT INTO wallets(user_id,currency,balance) VALUES(1,'RUB',500)");
$pdo->exec("INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,currency,description) VALUES(1,1,'credit',500,500,'RUB','Smoke test')");
assert((float)$pdo->query("SELECT balance FROM wallets WHERE id=1")->fetchColumn() === 500.0);
$pdo->exec("UPDATE services SET expires_at='2026-09-01 00:00:00',auto_renew=1,billing_cycle='monthly',renewal_price=100,currency='RUB' WHERE id=1");
$pdo->exec("INSERT INTO service_renewals(service_id,invoice_id,renewal_key,period_end,status) VALUES(1,1,'1-2026-09-01','2026-09-01','invoiced')");
assert((int)$pdo->query("SELECT COUNT(*) FROM service_renewals WHERE service_id=1")->fetchColumn() === 1);
$pdo->exec("INSERT INTO notifications(user_id,event_type,dedupe_key,subject,body) VALUES(1,'service_expiry','smoke-1','Expiry','Test')");
assert((int)$pdo->query("SELECT COUNT(*) FROM notifications WHERE status='pending'")->fetchColumn() === 1);
$pdo->exec("INSERT INTO discounts(code,type,value,minimum_amount,currency,max_uses) VALUES('TEST20','percent',20,50,'RUB',10)");
$pdo->exec("UPDATE orders SET subtotal=100,discount_amount=20,discount_id=1,discount_code='TEST20',amount=80 WHERE id=1");
$pdo->exec("INSERT INTO discount_redemptions(discount_id,order_id,user_id,code,discount_amount,currency) VALUES(1,1,1,'TEST20',20,'RUB')");
assert((float)$pdo->query("SELECT amount FROM orders WHERE id=1")->fetchColumn() === 80.0);
assert((int)$pdo->query("SELECT COUNT(*) FROM discount_redemptions")->fetchColumn() === 1);
$pdo->exec("UPDATE users SET country='RU' WHERE id=1");
$pdo->exec("INSERT INTO tax_rates(name,country,currency,rate,priority) VALUES('VAT','RU','RUB',20,10)");
$pdo->exec("UPDATE invoices SET tax_rate_id=1,tax_rate=20,tax_amount=20,total=120 WHERE id=1");
assert((float)$pdo->query("SELECT tax_amount FROM invoices WHERE id=1")->fetchColumn() === 20.0);
assert((float)$pdo->query("SELECT total FROM invoices WHERE id=1")->fetchColumn() === 120.0);
$pdo->exec("INSERT INTO api_tokens(name,token_prefix,token_hash,scopes,created_by) VALUES('Smoke','vo_live_smoke','" . hash('sha256','smoke') . "','[\"read\"]',1)");
assert((int)$pdo->query("SELECT COUNT(*) FROM api_tokens WHERE revoked_at IS NULL")->fetchColumn() === 1);
$pdo->exec("INSERT INTO api_request_logs(token_id,method,path,status_code,ip_address,duration_ms) VALUES(1,'GET','/api/v1/health',200,'127.0.0.1',3)");
assert((int)$pdo->query("SELECT COUNT(*) FROM api_request_logs WHERE status_code=200")->fetchColumn() === 1);
putenv('APP_KEY=smoke-test-key-at-least-32-characters');
$protected=VazinCMS\Webhook::protect('whsec_smoke');
assert(VazinCMS\Webhook::reveal($protected)==='whsec_smoke');
$pdo->prepare("INSERT INTO webhook_endpoints(name,url,secret_hash,secret_encrypted,events,created_by) VALUES('Smoke Hook','https://example.com/hook',:hash,:secret,'[\"webhook.test\"]',1)")->execute(['hash'=>hash('sha256','whsec_smoke'),'secret'=>$protected]);
assert(VazinCMS\Webhook::enqueue('webhook.test',['ok'=>true])===1);
assert((int)$pdo->query("SELECT COUNT(*) FROM webhook_deliveries WHERE status='pending'")->fetchColumn()===1);
$payload=(string)$pdo->query('SELECT payload FROM webhook_deliveries LIMIT 1')->fetchColumn();
assert(str_contains(VazinCMS\Webhook::signature($payload,'whsec_smoke',123),'v1='.hash_hmac('sha256','123.'.$payload,'whsec_smoke')));
$pdo->exec("INSERT INTO scheduled_tasks(name,task_type,interval_minutes,config,created_by) VALUES('Expiry','service_expiry',60,'{}',1)");
$runs=VazinCMS\Scheduler::runDue(1);
assert(($runs[0]['status']??null)==='succeeded');
assert((int)$pdo->query("SELECT COUNT(*) FROM scheduled_task_runs WHERE status='succeeded'")->fetchColumn()===1);
$pdo->exec("INSERT INTO users(name,email,password_hash,role,status) VALUES('Support','support@example.test','hash','support','active')");
assert(VazinCMS\Access::allowed(['id'=>2,'role'=>'support'],'support')===true);
assert(VazinCMS\Access::allowed(['id'=>2,'role'=>'support'],'finance')===false);
$pdo->exec("INSERT INTO staff_permissions(user_id,permission,is_granted,updated_by) VALUES(2,'finance',1,1)");
assert(VazinCMS\Access::allowed(['id'=>2,'role'=>'support'],'finance')===true);
$pdo->exec("INSERT INTO active_sessions(user_id,session_hash,ip_address,user_agent) VALUES(2,'smoke-session','127.0.0.1','Smoke')");
assert((int)$pdo->query("SELECT COUNT(*) FROM active_sessions WHERE revoked_at IS NULL")->fetchColumn()===1);
echo "Smoke tests: OK\n"; @unlink($db);
