<?php use VazinCMS\Security;$all=['fa'=>'فارسی','ar'=>'العربية','en'=>'English','ru'=>'Русский','tr'=>'Türkçe','hy'=>'Հայերեն','kk'=>'Қазақша','tg'=>'Тоҷикӣ','zh'=>'中文'];?>
<section class="page-head"><h1>هویت و تنظیمات سایت</h1><p>پروفایل نمایش، محتوای صفحه اصلی، اطلاعات تماس و زبان‌های همین سایت را مدیریت کنید. انتخاب قالب در بخش «قالب‌ها و ماژول‌ها» انجام می‌شود.</p></section>
<?php if($message):?><div class="alert success"><?=Security::e($message)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=Security::e($error)?></div><?php endif;?>
<form class="card" method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><h2>پروفایل و هویت</h2><div class="grid two">
<label>پروفایل نمایش<select name="site_profile"><option value="corporate" <?=($settings['site_profile']??'corporate')==='corporate'?'selected':''?>>شرکتی و خدماتی</option><option value="travel" <?=($settings['site_profile']??'')==='travel'?'selected':''?>>پلتفرم وایت‌لیبل سفر</option><option value="visa" <?=($settings['site_profile']??'')==='visa'?'selected':''?>>پلتفرم وایت‌لیبل ویزا</option><option value="pay" <?=($settings['site_profile']??'')==='pay'?'selected':''?>>پرداخت و کیف پول</option></select></label><label>رنگ اصلی<input type="color" name="primary_color" value="<?=Security::e($settings['primary_color']??'#3156d3')?>"></label>
<label>نام سایت<input name="site_name" required value="<?=Security::e($settings['site_name']??'')?>"></label><label>شعار<input name="site_tagline" value="<?=Security::e($settings['site_tagline']??'')?>"></label>
<label>نشانی لوگو<input name="logo_url" dir="ltr" placeholder="https://…" value="<?=Security::e($settings['logo_url']??'')?>"></label><label>ایمیل تماس<input type="email" dir="ltr" name="contact_email" value="<?=Security::e($settings['contact_email']??'')?>"></label>
<label>تلفن تماس<input dir="ltr" name="contact_phone" value="<?=Security::e($settings['contact_phone']??'')?>"></label><label>نشانی تماس<input name="contact_address" value="<?=Security::e($settings['contact_address']??'')?>"></label></div>
<label>توضیحات سایت<textarea name="site_description" rows="4"><?=Security::e($settings['site_description']??'')?></textarea></label>
<hr><h2>صفحه اصلی</h2><div class="grid two"><label>برچسب بالای عنوان<input name="hero_badge" value="<?=Security::e($settings['hero_badge']??'')?>"></label><label>عنوان اصلی<input name="hero_title" value="<?=Security::e($settings['hero_title']??'')?>"></label><label class="wide">توضیح کوتاه<textarea name="hero_text" rows="3"><?=Security::e($settings['hero_text']??'')?></textarea></label><label>متن دکمه اصلی<input name="primary_cta_label" value="<?=Security::e($settings['primary_cta_label']??'')?>"></label><label>پیوند دکمه اصلی<input dir="ltr" name="primary_cta_url" value="<?=Security::e($settings['primary_cta_url']??'')?>"></label><label>متن دکمه دوم<input name="secondary_cta_label" value="<?=Security::e($settings['secondary_cta_label']??'')?>"></label><label>پیوند دکمه دوم<input dir="ltr" name="secondary_cta_url" value="<?=Security::e($settings['secondary_cta_url']??'')?>"></label></div>
<details class="seo-box"><summary>محتوای پیشرفته صفحه اصلی (JSON)</summary><p>هر مورد به‌شکل <code>[["عنوان","توضیح"], ...]</code> وارد شود.</p><label>آمار<textarea dir="ltr" name="stats_json" rows="4"><?=Security::e($settings['stats_json']??'')?></textarea></label><label>امکانات<textarea dir="ltr" name="features_json" rows="6"><?=Security::e($settings['features_json']??'')?></textarea></label><label>مراحل کار<textarea dir="ltr" name="steps_json" rows="6"><?=Security::e($settings['steps_json']??'')?></textarea></label><label>پرسش‌های متداول<textarea dir="ltr" name="faq_json" rows="6"><?=Security::e($settings['faq_json']??'')?></textarea></label></details>
<hr><h2>شبکه‌های اجتماعی و فوتر</h2><div class="grid two"><label>تلگرام<input dir="ltr" name="social_telegram" value="<?=Security::e($settings['social_telegram']??'')?>"></label><label>اینستاگرام<input dir="ltr" name="social_instagram" value="<?=Security::e($settings['social_instagram']??'')?>"></label><label>یوتیوب<input dir="ltr" name="social_youtube" value="<?=Security::e($settings['social_youtube']??'')?>"></label><label>متن فوتر<input name="footer_text" value="<?=Security::e($settings['footer_text']??'')?>"></label></div>
<hr><h2>زبان‌ها</h2>
<fieldset><legend>زبان‌های فعال</legend><?php foreach($all as $code=>$label):?><label style="display:inline-block;margin:.5rem"><input type="checkbox" name="enabled_locales[]" value="<?=$code?>" <?=in_array($code,$enabledLocales,true)?'checked':''?>> <?=Security::e($label)?></label><?php endforeach;?></fieldset>
<label>زبان پیش‌فرض<select name="default_locale"><?php foreach($all as $code=>$label):?><option value="<?=$code?>" <?=$code===($settings['default_locale']??'fa')?'selected':''?>><?=Security::e($label)?></option><?php endforeach;?></select></label><button>ذخیره تنظیمات</button></form>
