<?php use VazinCMS\Security;$editing=is_array($edit);$languages=['fa'=>'فارسی','ar'=>'العربية','en'=>'English','ru'=>'Русский','tr'=>'Türkçe','hy'=>'Հայերեն','kk'=>'Қазақша','tg'=>'Тоҷикӣ','zh'=>'中文'];$published=count(array_filter($pages,fn($p)=>$p['status']==='published'));$publishedValue=!empty($edit['published_at'])?str_replace(' ','T',substr((string)$edit['published_at'],0,16)):'';?>
<section class="admin-title"><div><span class="eyebrow">مدیریت محتوا</span><h1>صفحه‌ها و نوشته‌ها</h1><p>صفحهٔ ثابت یا نوشته بسازید، تاریخ انتشار و داده‌های SEO را تنظیم و برای هر زبان منتشر کنید.</p></div><div class="title-actions"><span class="metric"><b><?=count($pages)?></b> کل محتوا</span><span class="metric success"><b><?=$published?></b> منتشرشده</span><a class="button secondary" href="/admin/menus">مدیریت منوها</a></div></section>
<?php if($error):?><div class="alert error"><?=Security::e($error)?></div><?php endif;?>
<section class="content-layout">
 <form class="editor-card" method="post" id="page-editor"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="id" value="<?=(int)($edit['id']??0)?>">
  <div class="card-head"><div><h2><?=$editing?'ویرایش محتوا':'ساخت محتوای جدید'?></h2><p><?=$editing?'تغییرات پس از ذخیره در سایت اعمال می‌شوند.':'نوع محتوا، عنوان و متن را وارد کنید.'?></p></div><?php if($editing):?><a class="button ghost" href="/admin/pages">محتوای جدید</a><?php endif;?></div>
  <div class="form-grid"><label>عنوان<input id="page-title" name="title" required maxlength="190" value="<?=Security::e($edit['title']??'')?>" placeholder="عنوان روشن و دقیق"></label><label>نشانی <small>فقط انگلیسی</small><div class="slug-field"><span>/</span><input id="page-slug" name="slug" dir="ltr" required maxlength="189" placeholder="article-slug" value="<?=Security::e($edit['slug']??'')?>"></div></label><label>نوع محتوا<select name="content_type"><option value="page" <?=($edit['content_type']??'page')==='page'?'selected':''?>>صفحهٔ ثابت</option><option value="post" <?=($edit['content_type']??'')==='post'?'selected':''?>>نوشته / پست</option></select></label><label>زبان<select name="locale"><?php foreach($languages as $locale=>$name):?><option value="<?=$locale?>" <?=$locale===($edit['locale']??'fa')?'selected':''?>><?=Security::e($name)?> · <?=$locale?></option><?php endforeach;?></select></label><label>وضعیت<select name="status"><option value="draft" <?=($edit['status']??'')==='draft'?'selected':''?>>پیش‌نویس</option><option value="published" <?=($edit['status']??'')==='published'?'selected':''?>>منتشرشده</option></select></label><label>تاریخ اصلی انتشار <small>برای نوشته</small><input type="datetime-local" name="published_at" value="<?=Security::e($publishedValue)?>"></label></div>
  <label class="switch-row"><input type="checkbox" name="is_home" <?=!empty($edit['is_home'])?'checked':''?>><span class="switch"></span><span><b>صفحه اصلی این زبان</b><small>فقط برای «صفحهٔ ثابت» اعمال می‌شود؛ نوشته‌ها هرگز خودکار صفحهٔ اصلی نمی‌شوند.</small></span></label>
  <div class="editor-label"><span>محتوا</span><span>Block Editor</span></div><div class="block-palette"><button type="button" data-add-block="paragraph">متن</button><button type="button" data-add-block="heading">عنوان</button><button type="button" data-add-block="list">فهرست</button><button type="button" data-add-block="image">تصویر</button><button type="button" data-add-block="gallery">گالری</button><button type="button" data-add-block="button">دکمه</button><button type="button" data-add-block="embed">جاسازی</button><button type="button" data-add-block="code">کد</button><button type="button" data-add-block="columns">ستون‌ها</button></div><input type="hidden" name="block_document" value="<?=Security::e($edit['block_document']??'')?>"><textarea id="page-body" name="body" hidden><?=Security::e($edit['body']??'')?></textarea><div id="block-editor-root" class="block-editor-root"></div><details class="seo-box" open><summary>سئو و اشتراک‌گذاری</summary><div class="form-grid"><label>عنوان SEO<input name="meta_title" maxlength="255" value="<?=Security::e($edit['meta_title']??'')?>"></label><label>توضیحات SEO<textarea name="meta_description" maxlength="320" rows="3"><?=Security::e($edit['meta_description']??'')?></textarea></label><label>Canonical URL<input name="canonical_url" dir="ltr" placeholder="https://example.com/fa/page/..." value="<?=Security::e($edit['canonical_url']??'')?>"></label><label>تصویر شاخص<input name="featured_image" dir="ltr" placeholder="/uploads/image.webp" value="<?=Security::e($edit['featured_image']??'')?>"></label><label>عنوان شبکه‌های اجتماعی<input name="og_title" maxlength="255" value="<?=Security::e($edit['og_title']??'')?>"></label><label>توضیح شبکه‌های اجتماعی<textarea name="og_description" maxlength="500" rows="3"><?=Security::e($edit['og_description']??'')?></textarea></label><label>نوع Schema<select name="schema_type"><?php foreach(['WebPage'=>'WebPage','Article'=>'Article','BlogPosting'=>'BlogPosting','NewsArticle'=>'NewsArticle'] as $value=>$label):?><option value="<?=$value?>" <?=$value===($edit['schema_type']??(($edit['content_type']??'page')==='post'?'Article':'WebPage'))?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label class="switch-row"><input type="checkbox" name="robots_index" value="1" <?=!$editing||!empty($edit['robots_index'])?'checked':''?>><span class="switch"></span><span><b>اجازهٔ ایندکس</b></span></label><label class="switch-row"><input type="checkbox" name="robots_follow" value="1" <?=!$editing||!empty($edit['robots_follow'])?'checked':''?>><span class="switch"></span><span><b>دنبال‌کردن پیوندها</b></span></label></div></details>
  <div class="sticky-actions"><button type="submit">ذخیره صفحه</button><?php if($editing):?><a class="button secondary" target="_blank" href="/<?=Security::e($edit['locale'])?>/page/<?=Security::e($edit['slug'])?>">مشاهده صفحه</a><a class="button ghost" href="/admin/pages">انصراف</a><?php endif;?></div>
 </form>
 <aside class="list-card"><div class="card-head"><div><h2>صفحه‌های موجود</h2><p>برای ویرایش روی هر صفحه بزنید.</p></div></div><div class="list-filter"><input id="page-search" type="search" placeholder="جست‌وجوی عنوان یا نشانی…"><select id="locale-filter"><option value="">همه زبان‌ها</option><?php foreach($languages as $locale=>$name):?><option value="<?=$locale?>"><?=Security::e($name)?></option><?php endforeach;?></select></div><div class="page-list" id="page-list"><?php foreach($pages as $page):?><article class="page-item <?=$editing&&(int)$edit['id']===(int)$page['id']?'active':''?>" data-search="<?=Security::e(mb_strtolower($page['title'].' '.$page['slug']))?>" data-locale="<?=Security::e($page['locale'])?>"><a class="page-main" href="/admin/pages?edit=<?=(int)$page['id']?>"><div><strong><?=Security::e($page['title'])?></strong><?php if($page['is_home']):?><span class="home-badge">خانه</span><?php endif;?></div><code>/<?=Security::e($page['locale'].'/'.$page['slug'])?></code><span class="status <?=Security::e($page['status'])?>"><?=$page['status']==='published'?'منتشرشده':'پیش‌نویس'?></span></a><form method="post" data-confirm="<?=Security::e('صفحه «'.$page['title'].'» حذف شود؟')?>"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$page['id']?>"><button class="icon-danger" title="حذف" aria-label="حذف">×</button></form></article><?php endforeach;?><?php if(!$pages):?><div class="empty-state"><b>هنوز صفحه‌ای وجود ندارد</b><p>اولین صفحه را از فرم کناری بسازید.</p></div><?php endif;?></div></aside>
</section>

<script src="/assets/block-editor-120.js?v=10.12.0" defer></script>
