<?php use VazinCMS\{Access,Security}; ?>
<section class="title"><div><h1>تیم و دسترسی‌ها</h1><p>مدیران، مجوزها و نشست‌های فعال</p></div></section>
<?php if($message):?><div class="success"><?=Security::e($message)?></div><?php endif;?>
<?php if($error):?><div class="alert"><?=Security::e($error)?></div><?php endif;?>
<section class="split">
<div class="panel"><h2>عضو جدید تیم</h2><form method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="create"><label>نام<input name="name" required minlength="2"></label><label>ایمیل<input type="email" name="email" required></label><label>رمز اولیه<input type="password" name="password" minlength="12" required></label><label>نقش<select name="role"><option value="support">پشتیبان</option><option value="admin">مدیر</option></select></label><button>ایجاد عضو</button></form></div>
<div class="panel"><h2>اعضای تیم</h2><div class="table"><table><thead><tr><th>نام</th><th>نقش</th><th>وضعیت</th><th>نشست فعال</th><th></th></tr></thead><tbody><?php foreach($staff as $member):?><tr><td><?=Security::e($member['name'])?><small><?=Security::e($member['email'])?></small></td><td><?=Security::e($member['role'])?></td><td><span class="status <?=$member['status']?>"><?=Security::e($member['status'])?></span></td><td><?=(int)$member['session_count']?></td><td><a href="?member=<?=$member['id']?>">مدیریت</a></td></tr><?php endforeach;?></tbody></table></div></div>
</section>
<?php if($selected):?><section class="panel"><h2>دسترسی‌های <?=Security::e($selected['name'])?></h2><form method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="permissions"><input type="hidden" name="member_id" value="<?=$selected['id']?>"><div class="permission-grid"><?php foreach(Access::definitions() as $key=>$label):?><label><input type="checkbox" name="permissions[]" value="<?=$key?>" <?=in_array($key,$selectedPermissions,true)?'checked':''?>> <?=Security::e($label)?></label><?php endforeach;?></div><button>ذخیره دسترسی‌ها</button></form><hr><div class="actions"><form method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="member_id" value="<?=$selected['id']?>"><button class="secondary"><?=$selected['status']==='active'?'تعلیق حساب':'فعال‌کردن حساب'?></button></form><form method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="revoke"><input type="hidden" name="member_id" value="<?=$selected['id']?>"><button class="danger">خروج اجباری از همه دستگاه‌ها</button></form></div><h3>نشست‌های اخیر</h3><div class="table"><table><thead><tr><th>IP</th><th>دستگاه</th><th>آخرین فعالیت</th><th>وضعیت</th></tr></thead><tbody><?php foreach($sessions as $session):?><tr><td><?=Security::e((string)$session['ip_address'])?></td><td><?=Security::e(mb_strimwidth((string)$session['user_agent'],0,80,'…'))?></td><td><?=Security::e((string)$session['last_seen_at'])?></td><td><?=$session['revoked_at']?'لغوشده':'فعال'?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
