<?php use VazinCMS\Security; ?>
<section class="title"><div><h1><?=Security::e($profile['name'])?> <small>#<?=$profile['id']?></small></h1><p><?=Security::e($profile['email'])?> · <?=Security::e((string)$profile['phone'])?></p></div><a class="button secondary" href="/admin/users">بازگشت</a></section>
<?php if($error):?><div class="alert"><?=Security::e($error)?></div><?php endif;?>
<?php if($walletUpdated):?><div class="notice">تغییر موجودی با موفقیت ثبت شد.</div><?php endif;?>
<section class="customer-summary"><?php foreach(['services'=>'سرویس','orders'=>'سفارش','invoices'=>'فاکتور','tickets'=>'تیکت'] as $key=>$label):?><div class="panel metric"><strong><?=$summary[$key]?></strong><span><?=$label?></span></div><?php endforeach;?></section>
<section class="split"><div class="panel"><h2>پروفایل</h2><form method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="save"><?php foreach(['name'=>'نام','email'=>'ایمیل','phone'=>'تلفن','company'=>'شرکت','country'=>'کشور'] as $k=>$l):?><label><?=$l?><input name="<?=$k?>" value="<?=Security::e((string)$profile[$k])?>" <?=$k==='email'?'type="email"':''?> <?=$k==='name'||$k==='email'?'required':''?>></label><?php endforeach;?><label>یادداشت<textarea name="notes" rows="5"><?=Security::e((string)$profile['notes'])?></textarea></label><button>ذخیره پروفایل</button></form><hr><form method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="status"><label>وضعیت<select name="status"><?php foreach(['active'=>'فعال','pending'=>'در انتظار','suspended'=>'تعلیق','closed'=>'بسته'] as $v=>$l):?><option value="<?=$v?>" <?=$profile['status']===$v?'selected':''?>><?=$l?></option><?php endforeach;?></select></label><button class="danger">تغییر وضعیت</button></form></div><div>
<section class="panel"><h2>کیف پول‌ها</h2><div class="quick-cards"><?php foreach($wallets as $w):?><a href="/admin/wallets/<?=$w['id']?>"><strong><?=number_format((float)$w['balance'],2)?></strong><span><?=Security::e($w['currency'])?></span></a><?php endforeach;?><?php if(!$wallets):?><p class="muted">کیف پولی ثبت نشده است.</p><?php endif;?></div><?php if($wallets&&in_array($user['role'],['owner','admin'],true)):?><hr><h3>تغییر موجودی</h3><form method="post"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="action" value="wallet_adjust"><input type="hidden" name="request_key" value="<?=Security::e($walletRequestKey)?>"><div class="form-grid"><label>کیف پول<select name="wallet_id" required><?php foreach($wallets as $w):?><option value="<?=$w['id']?>"><?=Security::e($w['currency'])?> — <?=number_format((float)$w['balance'],2)?></option><?php endforeach;?></select></label><label>نوع<select name="kind"><option value="credit">افزایش موجودی</option><option value="debit">کاهش موجودی</option></select></label><label>مبلغ<input name="amount" type="number" min="0.01" step="0.01" required></label></div><label>دلیل تغییر<textarea name="description" rows="2" minlength="4" required placeholder="مثلاً اصلاح پرداخت دستی یا بازپرداخت"></textarea></label><button>ثبت تغییر موجودی</button><p class="muted">هر درخواست فقط یک‌بار ثبت می‌شود و در گزارش حسابرسی باقی می‌ماند.</p></form><?php endif;?></section>
<section class="panel stack-panel"><h2>آخرین گردش کیف پول</h2><div class="table"><table><thead><tr><th>زمان</th><th>نوع</th><th>مبلغ</th><th>مانده</th><th>توضیح</th><th>ثبت‌کننده</th></tr></thead><tbody><?php foreach($walletTransactions as $tx):?><tr><td><?=Security::e((string)$tx['created_at'])?></td><td><?=$tx['type']==='credit'?'افزایش':'کاهش'?></td><td><?=number_format((float)$tx['amount'],2)?> <?=Security::e($tx['currency'])?></td><td><?=number_format((float)$tx['balance_after'],2)?></td><td><?=Security::e($tx['description'])?></td><td><?=Security::e((string)($tx['staff_name']?:'سیستم'))?></td></tr><?php endforeach;?><?php if(!$walletTransactions):?><tr><td colspan="6" class="muted">گردش مالی ثبت نشده است.</td></tr><?php endif;?></tbody></table></div></section>
<section class="panel stack-panel"><h2>سفارش‌های اخیر</h2><div class="table"><table><thead><tr><th>شماره</th><th>مبلغ</th><th>وضعیت</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><a href="/admin/orders/<?=$o['id']?>"><?=Security::e($o['order_number'])?></a></td><td><?=number_format((float)$o['amount'],2)?> <?=Security::e($o['currency'])?></td><td><?=Security::e($o['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel stack-panel"><h2>فاکتورهای اخیر</h2><div class="table"><table><thead><tr><th>شماره</th><th>مبلغ</th><th>وضعیت</th></tr></thead><tbody><?php foreach($invoices as $i):?><tr><td><a href="/admin/invoices/<?=$i['id']?>"><?=Security::e($i['invoice_number'])?></a></td><td><?=number_format((float)$i['total'],2)?> <?=Security::e($i['currency'])?></td><td><?=Security::e($i['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel stack-panel"><h2>سرویس‌ها</h2><div class="table"><table><thead><tr><th>نام</th><th>شناسه</th><th>وضعیت</th><th>انقضا</th></tr></thead><tbody><?php foreach($services as $s):?><tr><td><?=Security::e($s['name'])?></td><td><?=Security::e((string)$s['identifier'])?></td><td><?=Security::e($s['status'])?></td><td><?=Security::e((string)$s['expires_at'])?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel stack-panel"><h2>آخرین تیکت‌ها</h2><div class="table"><table><thead><tr><th>عنوان</th><th>اولویت</th><th>وضعیت</th></tr></thead><tbody><?php foreach($tickets as $t):?><tr><td><a href="/admin/tickets/<?=$t['id']?>"><?=Security::e($t['subject'])?></a></td><td><?=Security::e($t['priority'])?></td><td><?=Security::e($t['status'])?></td></tr><?php endforeach;?></tbody></table></div></section>
</div></section>
