CREATE TABLE IF NOT EXISTS schema_migrations (version VARCHAR(32) PRIMARY KEY, applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL CHECK(role IN ('owner','admin','support','client')),
 status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended','pending')), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS one_owner ON users(role) WHERE role='owner';
CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, slug VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL,
 type VARCHAR(40) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'detached', current_version VARCHAR(40), endpoint VARCHAR(500), api_key_hash VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
 action VARCHAR(100) NOT NULL, description TEXT NOT NULL, ip_address VARCHAR(64), metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);
CREATE TABLE IF NOT EXISTS login_attempts (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, attempt_key VARCHAR(64) NOT NULL, email VARCHAR(255) NOT NULL,
 ip_address VARCHAR(64), succeeded SMALLINT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_login_limit ON login_attempts(attempt_key,created_at DESC);
