<?php
declare(strict_types=1);
namespace VazinCMS\Controllers;
use PDO; use Throwable; use VazinCMS\{Access,Audit,Auth,Database,DeliveryPolicy,ReleaseChannel,Scheduler,Security,View,Webhook};

final class AdminController
{
    private function staff(): array { return Auth::requireUser(['owner','admin','support']); }
    public function team(): void
    {
        $user=Auth::requireUser(['owner']);$pdo=Database::connection();$error=null;$message=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$action=(string)($_POST['action']??'');$memberId=(int)($_POST['member_id']??0);
            if($action==='create'){
                $name=trim((string)($_POST['name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$password=(string)($_POST['password']??'');$role=(string)($_POST['role']??'support');
                if(mb_strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12||!in_array($role,['admin','support'],true))$error='اطلاعات عضو تیم معتبر نیست.';
                else try{$pdo->prepare("INSERT INTO users(name,email,password_hash,role,status) VALUES(:name,:email,:hash,:role,'active')")->execute(['name'=>$name,'email'=>$email,'hash'=>password_hash($password,PASSWORD_DEFAULT),'role'=>$role]);Audit::log('team.member_created','عضو تیم ساخته شد',(int)$user['id'],['target_id'=>$pdo->lastInsertId(),'role'=>$role]);header('Location: /admin/team');return;}catch(Throwable){$error='این ایمیل قبلاً ثبت شده است.';}
            } elseif($memberId>0){
                $check=$pdo->prepare("SELECT id,status FROM users WHERE id=:id AND role IN ('admin','support')");$check->execute(['id'=>$memberId]);$member=$check->fetch();if(!$member)$this->missing();
                if($action==='permissions'){$permissions=array_values(array_intersect((array)($_POST['permissions']??[]),array_keys(Access::definitions())));$pdo->beginTransaction();try{$pdo->prepare('DELETE FROM staff_permissions WHERE user_id=:id')->execute(['id'=>$memberId]);$insert=$pdo->prepare('INSERT INTO staff_permissions(user_id,permission,is_granted,updated_by) VALUES(:uid,:permission,1,:owner)');foreach($permissions as $permission)$insert->execute(['uid'=>$memberId,'permission'=>$permission,'owner'=>$user['id']]);$pdo->commit();Audit::log('team.permissions_updated','دسترسی‌های عضو تیم ویرایش شد',(int)$user['id'],['target_id'=>$memberId,'permissions'=>$permissions]);$message='دسترسی‌ها ذخیره شد.';}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
                elseif($action==='toggle'){$new=$member['status']==='active'?'suspended':'active';$pdo->prepare('UPDATE users SET status=:status,session_version=session_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['status'=>$new,'id'=>$memberId]);$pdo->prepare('UPDATE active_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=:id AND revoked_at IS NULL')->execute(['id'=>$memberId]);Audit::log('team.status_changed','وضعیت عضو تیم تغییر کرد',(int)$user['id'],['target_id'=>$memberId,'status'=>$new]);header('Location: /admin/team?member='.$memberId);return;}
                elseif($action==='revoke'){$pdo->prepare('UPDATE users SET session_version=session_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$memberId]);$pdo->prepare('UPDATE active_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=:id AND revoked_at IS NULL')->execute(['id'=>$memberId]);Audit::log('team.sessions_revoked','نشست‌های عضو تیم لغو شد',(int)$user['id'],['target_id'=>$memberId]);$message='تمام نشست‌های عضو تیم لغو شد.';}
            }
        }
        $staff=$pdo->query("SELECT u.id,u.name,u.email,u.role,u.status,COUNT(s.id) session_count FROM users u LEFT JOIN active_sessions s ON s.user_id=u.id AND s.revoked_at IS NULL WHERE u.role IN ('owner','admin','support') GROUP BY u.id,u.name,u.email,u.role,u.status ORDER BY CASE u.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,u.id")->fetchAll();
        $selected=null;$selectedPermissions=[];$sessions=[];$selectedId=(int)($_GET['member']??$_POST['member_id']??0);
        if($selectedId>0){$s=$pdo->prepare("SELECT id,name,email,role,status FROM users WHERE id=:id AND role IN ('admin','support')");$s->execute(['id'=>$selectedId]);$selected=$s->fetch()?:null;if($selected){$p=$pdo->prepare('SELECT permission FROM staff_permissions WHERE user_id=:id AND is_granted=1');$p->execute(['id'=>$selectedId]);$selectedPermissions=$p->fetchAll(PDO::FETCH_COLUMN);if($selectedPermissions===[])$selectedPermissions=array_values(array_filter(array_keys(Access::definitions()),fn($permission)=>Access::allowed($selected,$permission)));$s=$pdo->prepare('SELECT ip_address,user_agent,last_seen_at,revoked_at FROM active_sessions WHERE user_id=:id ORDER BY id DESC LIMIT 20');$s->execute(['id'=>$selectedId]);$sessions=$s->fetchAll();}}
        View::render('team',compact('user','staff','selected','selectedPermissions','sessions','error','message'));
    }
    public function dashboard(): void
    {
        $user=$this->staff(); $pdo=Database::connection();
        $stats=['users'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='client'")->fetchColumn(),'services'=>(int)$pdo->query("SELECT COUNT(*) FROM services WHERE status='active'")->fetchColumn(),'orders'=>(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status IN ('pending','paid','processing')")->fetchColumn(),'tickets'=>(int)$pdo->query("SELECT COUNT(*) FROM tickets WHERE status<>'closed'")->fetchColumn()];
        $events=$pdo->query('SELECT action,description,created_at FROM audit_logs ORDER BY id DESC LIMIT 8')->fetchAll(); $releaseChannel=ReleaseChannel::stable(); View::render('dashboard',compact('user','stats','events','releaseChannel'));
    }
    public function users(): void
    {
        $user=$this->staff(); $pdo=Database::connection(); $error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf(); if(!in_array($user['role'],['owner','admin'],true))$this->deny();
            $name=trim((string)($_POST['name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$role=(string)($_POST['role']??'client');$password=(string)($_POST['password']??'');
            if(mb_strlen($name)<2||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12||!in_array($role,['admin','support','client'],true))$error='اطلاعات کاربر کامل یا معتبر نیست.';
            else try{$s=$pdo->prepare("INSERT INTO users(name,email,password_hash,role,status) VALUES(:name,:email,:hash,:role,'active')");$s->execute(['name'=>$name,'email'=>$email,'hash'=>password_hash($password,PASSWORD_DEFAULT),'role'=>$role]);Audit::log('user.created','کاربر جدید ساخته شد',(int)$user['id'],['target_id'=>$pdo->lastInsertId(),'email'=>$email,'role'=>$role]);header('Location: /admin/users');return;}catch(Throwable){$error='این ایمیل قبلاً ثبت شده است.';}
        }
        $q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'');$role=(string)($_GET['role']??'client');$page=max(1,(int)($_GET['page']??1));$limit=20;$where=[];$params=[];
        if($q!==''){$where[]='(CAST(id AS TEXT)=:exact OR name LIKE :q OR email LIKE :q OR phone LIKE :q OR company LIKE :q)';$params['exact']=$q;$params['q']='%'.$q.'%';}
        if(in_array($status,['active','suspended','pending','closed'],true)){$where[]='status=:status';$params['status']=$status;}
        if(in_array($role,['owner','admin','support','client'],true)){$where[]='role=:role';$params['role']=$role;}
        $sql=$where?' WHERE '.implode(' AND ',$where):'';$count=$pdo->prepare('SELECT COUNT(*) FROM users'.$sql);$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$limit));$page=min($page,$pages);
        $s=$pdo->prepare('SELECT id,name,email,phone,company,role,status,created_at FROM users'.$sql.' ORDER BY id DESC LIMIT '.$limit.' OFFSET '.(($page-1)*$limit));$s->execute($params);$users=$s->fetchAll();View::render('users',compact('user','users','error','q','status','role','page','pages','total'));
    }
    public function user(int $id): void
    {
        $user=$this->staff();$pdo=Database::connection();$s=$pdo->prepare('SELECT id,name,email,phone,company,country,notes,role,status,created_at FROM users WHERE id=:id');$s->execute(['id'=>$id]);$profile=$s->fetch();if(!$profile)$this->missing();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();if(!in_array($user['role'],['owner','admin'],true))$this->deny();$action=(string)($_POST['action']??'save');
            if($action==='status'){$new=(string)($_POST['status']??'');if((int)$profile['id']===(int)$user['id']||!in_array($new,['active','suspended','pending','closed'],true))$error='این تغییر وضعیت مجاز نیست.';else{$pdo->prepare('UPDATE users SET status=:status,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['status'=>$new,'id'=>$id]);Audit::log('user.status_changed','وضعیت حساب تغییر کرد',(int)$user['id'],['target_id'=>$id,'from'=>$profile['status'],'to'=>$new]);header('Location: /admin/users/'.$id);return;}}
            elseif($action==='wallet_adjust'){
                $walletId=(int)($_POST['wallet_id']??0);$kind=(string)($_POST['kind']??'credit');$amount=round((float)($_POST['amount']??0),2);$description=trim((string)($_POST['description']??''));$requestKey=trim((string)($_POST['request_key']??''));
                if($walletId<1||!in_array($kind,['credit','debit'],true)||$amount<=0||mb_strlen($description)<4||!preg_match('/^[a-f0-9]{32}$/',$requestKey))$error='کیف پول، مبلغ یا دلیل تغییر معتبر نیست.';
                else{$pdo->beginTransaction();try{$lock=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'?' FOR UPDATE':'';$ws=$pdo->prepare('SELECT id,user_id,currency,balance FROM wallets WHERE id=:wallet AND user_id=:uid'.$lock);$ws->execute(['wallet'=>$walletId,'uid'=>$id]);$wallet=$ws->fetch();if(!$wallet)throw new \RuntimeException('کیف پول انتخاب‌شده متعلق به این مشتری نیست.');$reference='ADMIN-'.$requestKey;$duplicate=$pdo->prepare('SELECT id FROM wallet_transactions WHERE reference=:reference');$duplicate->execute(['reference'=>$reference]);if($duplicate->fetchColumn())throw new \RuntimeException('این درخواست قبلاً ثبت شده است؛ صفحه را تازه‌سازی کنید.');$before=round((float)$wallet['balance'],2);$after=round($before+($kind==='credit'?$amount:-$amount),2);if($after<0)throw new \RuntimeException('موجودی کیف پول کافی نیست.');$pdo->prepare('UPDATE wallets SET balance=:balance,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['balance'=>$after,'id'=>$walletId]);$pdo->prepare('INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,currency,reference,description,created_by) VALUES(:wallet,:uid,:type,:amount,:balance,:currency,:reference,:description,:staff)')->execute(['wallet'=>$walletId,'uid'=>$id,'type'=>$kind,'amount'=>$amount,'balance'=>$after,'currency'=>$wallet['currency'],'reference'=>$reference,'description'=>$description,'staff'=>$user['id']]);$pdo->commit();Audit::log('customer.wallet_adjusted','موجودی مشتری از پروفایل اصلاح شد',(int)$user['id'],['target_id'=>$id,'wallet_id'=>$walletId,'type'=>$kind,'amount'=>$amount,'balance_before'=>$before,'balance_after'=>$after,'currency'=>$wallet['currency'],'reason'=>$description]);header('Location: /admin/users/'.$id.'?wallet=updated');return;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof \RuntimeException?$e->getMessage():'تغییر موجودی ثبت نشد.';}}
            } else{$data=['name'=>trim((string)($_POST['name']??'')),'email'=>strtolower(trim((string)($_POST['email']??''))),'phone'=>trim((string)($_POST['phone']??'')),'company'=>trim((string)($_POST['company']??'')),'country'=>trim((string)($_POST['country']??'')),'notes'=>trim((string)($_POST['notes']??'')),'id'=>$id];if(mb_strlen($data['name'])<2||!filter_var($data['email'],FILTER_VALIDATE_EMAIL))$error='نام یا ایمیل معتبر نیست.';else try{$pdo->prepare('UPDATE users SET name=:name,email=:email,phone=:phone,company=:company,country=:country,notes=:notes,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute($data);Audit::log('user.updated','پروفایل کاربر ویرایش شد',(int)$user['id'],['target_id'=>$id]);header('Location: /admin/users/'.$id);return;}catch(Throwable){$error='ایمیل تکراری است.';}}
        }
        $t=$pdo->prepare('SELECT id,subject,status,priority,updated_at FROM tickets WHERE user_id=:id ORDER BY updated_at DESC LIMIT 10');$t->execute(['id'=>$id]);$tickets=$t->fetchAll();
        $s=$pdo->prepare('SELECT id,name,status,identifier,expires_at FROM services WHERE user_id=:id ORDER BY id DESC LIMIT 10');$s->execute(['id'=>$id]);$services=$s->fetchAll();
        $s=$pdo->prepare('SELECT id,order_number,status,amount,currency,created_at FROM orders WHERE user_id=:id ORDER BY id DESC LIMIT 10');$s->execute(['id'=>$id]);$orders=$s->fetchAll();
        $s=$pdo->prepare('SELECT id,invoice_number,status,total,currency,due_at FROM invoices WHERE user_id=:id ORDER BY id DESC LIMIT 10');$s->execute(['id'=>$id]);$invoices=$s->fetchAll();
        $s=$pdo->prepare('SELECT id,currency,balance,updated_at FROM wallets WHERE user_id=:id ORDER BY currency');$s->execute(['id'=>$id]);$wallets=$s->fetchAll();
        $s=$pdo->prepare('SELECT wt.id,wt.wallet_id,wt.type,wt.amount,wt.balance_after,wt.currency,wt.description,wt.reference,wt.created_at,u.name staff_name FROM wallet_transactions wt LEFT JOIN users u ON u.id=wt.created_by WHERE wt.user_id=:id ORDER BY wt.id DESC LIMIT 20');$s->execute(['id'=>$id]);$walletTransactions=$s->fetchAll();
        $summary=['services'=>count($services),'orders'=>(int)$pdo->query('SELECT COUNT(*) FROM orders WHERE user_id='.(int)$id)->fetchColumn(),'invoices'=>(int)$pdo->query('SELECT COUNT(*) FROM invoices WHERE user_id='.(int)$id)->fetchColumn(),'tickets'=>(int)$pdo->query('SELECT COUNT(*) FROM tickets WHERE user_id='.(int)$id)->fetchColumn()];
        $walletUpdated=($_GET['wallet']??'')==='updated';$walletRequestKey=bin2hex(random_bytes(16));
        View::render('user-profile',compact('user','profile','tickets','services','orders','invoices','wallets','walletTransactions','walletUpdated','walletRequestKey','summary','error'));
    }
    public function products(): void
    {
        $user=Auth::requireUser(['owner','admin']);$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$slug=strtolower(trim((string)($_POST['slug']??'')));$type=(string)($_POST['type']??'service');$price=(float)($_POST['price_amount']??0);$currency=strtoupper(trim((string)($_POST['currency']??'RUB')));$cycle=(string)($_POST['billing_cycle']??'monthly');$description=trim((string)($_POST['description']??''));$active=isset($_POST['is_active'])?1:0;if(mb_strlen($name)<2||!preg_match('/^[a-z0-9][a-z0-9-]{1,99}$/',$slug)||$price<0||!preg_match('/^[A-Z]{3,8}$/',$currency)||!in_array($cycle,['one_time','monthly','quarterly','yearly'],true))$error='اطلاعات محصول معتبر نیست.';else try{$data=['slug'=>$slug,'name'=>$name,'type'=>$type,'description'=>$description,'price'=>$price,'currency'=>$currency,'cycle'=>$cycle,'active'=>$active];if($id>0){$data['id']=$id;$pdo->prepare('UPDATE products SET slug=:slug,name=:name,type=:type,description=:description,price_amount=:price,currency=:currency,billing_cycle=:cycle,is_active=:active,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute($data);$action='product.updated';}else{$pdo->prepare("INSERT INTO products(slug,name,type,status,description,price_amount,currency,billing_cycle,is_active) VALUES(:slug,:name,:type,'detached',:description,:price,:currency,:cycle,:active)")->execute($data);$id=(int)$pdo->lastInsertId();$action='product.created';}Audit::log($action,'محصول ذخیره شد',(int)$user['id'],['product_id'=>$id]);header('Location: /admin/products');return;}catch(Throwable){$error='شناسه محصول تکراری یا اطلاعات نامعتبر است.';}}
        $products=$pdo->query('SELECT id,slug,name,type,status,price_amount,currency,billing_cycle,is_active,current_version FROM products ORDER BY id DESC')->fetchAll();View::render('products',compact('user','products','error'));
    }
    public function orders(): void
    {
        $user=$this->staff();$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$uid=(int)($_POST['user_id']??0);$pid=(int)($_POST['product_id']??0);$code=strtoupper(trim((string)($_POST['discount_code']??'')));
            $p=$pdo->prepare('SELECT id,name,price_amount,currency FROM products WHERE id=:id AND is_active=1');$p->execute(['id'=>$pid]);$product=$p->fetch();
            if($uid<1||!$product)$error='مشتری یا محصول معتبر نیست.';else{$pdo->beginTransaction();try{
                $subtotal=round((float)$product['price_amount'],2);$discount=0.0;$discountId=null;
                if($code!==''){$lock=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'?' FOR UPDATE':'';$d=$pdo->prepare("SELECT * FROM discounts WHERE code=:code AND is_active=1 AND (starts_at IS NULL OR starts_at<=CURRENT_TIMESTAMP) AND (expires_at IS NULL OR expires_at>=CURRENT_TIMESTAMP)".$lock);$d->execute(['code'=>$code]);$coupon=$d->fetch();if(!$coupon||($coupon['currency']&&$coupon['currency']!==$product['currency'])||($coupon['max_uses']!==null&&(int)$coupon['used_count']>=(int)$coupon['max_uses'])||$subtotal<(float)$coupon['minimum_amount'])throw new \RuntimeException('کد تخفیف معتبر نیست یا شرایط استفاده را ندارد.');$discount=$coupon['type']==='percent'?round($subtotal*min(100,(float)$coupon['value'])/100,2):min($subtotal,round((float)$coupon['value'],2));$discountId=(int)$coupon['id'];}
                $amount=max(0,round($subtotal-$discount,2));$number='VO-'.gmdate('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));
                $s=$pdo->prepare("INSERT INTO orders(order_number,user_id,product_id,product_name,subtotal,discount_amount,discount_id,discount_code,amount,currency,status,notes,created_by) VALUES(:num,:uid,:pid,:name,:subtotal,:discount,:discount_id,:code,:amount,:currency,'pending',:notes,:staff)");$s->execute(['num'=>$number,'uid'=>$uid,'pid'=>$pid,'name'=>$product['name'],'subtotal'=>$subtotal,'discount'=>$discount,'discount_id'=>$discountId,'code'=>$discountId?$code:null,'amount'=>$amount,'currency'=>$product['currency'],'notes'=>trim((string)($_POST['notes']??'')),'staff'=>$user['id']]);$id=(int)$pdo->lastInsertId();
                if($discountId){$pdo->prepare('UPDATE discounts SET used_count=used_count+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$discountId]);$pdo->prepare('INSERT INTO discount_redemptions(discount_id,order_id,user_id,code,discount_amount,currency) VALUES(:discount,:order,:user,:code,:amount,:currency)')->execute(['discount'=>$discountId,'order'=>$id,'user'=>$uid,'code'=>$code,'amount'=>$discount,'currency'=>$product['currency']]);}
                $pdo->commit();Audit::log('order.created','سفارش جدید ساخته شد',(int)$user['id'],['order_id'=>$id,'number'=>$number,'discount'=>$discount,'discount_code'=>$discountId?$code:null]);header('Location: /admin/orders/'.$id);return;
            }catch(\RuntimeException $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
        }
        $status=(string)($_GET['status']??'');$where='';$params=[];if(in_array($status,['pending','paid','processing','completed','cancelled','refunded'],true)){$where=' WHERE o.status=:status';$params['status']=$status;}$s=$pdo->prepare('SELECT o.*,u.name customer FROM orders o JOIN users u ON u.id=o.user_id'.$where.' ORDER BY o.id DESC LIMIT 200');$s->execute($params);$orders=$s->fetchAll();$clients=$pdo->query("SELECT id,name,email FROM users WHERE role='client' AND status='active' ORDER BY name")->fetchAll();$products=$pdo->query('SELECT id,name,price_amount,currency FROM products WHERE is_active=1 ORDER BY name')->fetchAll();View::render('orders',compact('user','orders','clients','products','error','status'));
    }
    public function order(int $id): void
    {
        $user=$this->staff();$pdo=Database::connection();$s=$pdo->prepare('SELECT o.*,u.name customer,u.email FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=:id');$s->execute(['id'=>$id]);$order=$s->fetch();if(!$order)$this->missing();
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$status=(string)($_POST['status']??'');if(!in_array($status,['pending','paid','processing','completed','cancelled','refunded'],true))$this->deny();$pdo->beginTransaction();try{$pdo->prepare('UPDATE orders SET status=:status,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['status'=>$status,'id'=>$id]);if($status==='completed'){$check=$pdo->prepare('SELECT id FROM services WHERE order_id=:id');$check->execute(['id'=>$id]);if(!$check->fetchColumn())$pdo->prepare("INSERT INTO services(user_id,product_id,order_id,name,status,started_at) VALUES(:uid,:pid,:oid,:name,'active',CURRENT_TIMESTAMP)")->execute(['uid'=>$order['user_id'],'pid'=>$order['product_id'],'oid'=>$id,'name'=>$order['product_name']]);}$pdo->commit();Audit::log('order.status_changed','وضعیت سفارش تغییر کرد',(int)$user['id'],['order_id'=>$id,'from'=>$order['status'],'to'=>$status]);header('Location: /admin/orders/'.$id);return;}catch(Throwable $e){$pdo->rollBack();throw $e;}}
        $v=$pdo->prepare('SELECT id,name,status,identifier,expires_at FROM services WHERE order_id=:id');$v->execute(['id'=>$id]);$service=$v->fetch();View::render('order',compact('user','order','service'));
    }
    public function discounts(): void
    {
        $user=Auth::requireUser(['owner','admin']);$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);
            if($action==='toggle'){$pdo->prepare('UPDATE discounts SET is_active=CASE WHEN is_active=1 THEN 0 ELSE 1 END,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$id]);Audit::log('discount.toggled','وضعیت کد تخفیف تغییر کرد',(int)$user['id'],['discount_id'=>$id]);header('Location: /admin/discounts');return;}
            $code=strtoupper(trim((string)($_POST['code']??'')));$type=(string)($_POST['type']??'percent');$value=round((float)($_POST['value']??0),2);$minimum=round((float)($_POST['minimum_amount']??0),2);$currency=strtoupper(trim((string)($_POST['currency']??'')));$maxUses=trim((string)($_POST['max_uses']??''));$starts=trim((string)($_POST['starts_at']??''));$expires=trim((string)($_POST['expires_at']??''));
            if(!preg_match('/^[A-Z0-9_-]{3,40}$/',$code)||!in_array($type,['percent','fixed'],true)||$value<=0||($type==='percent'&&$value>100)||$minimum<0||($currency!==''&&!preg_match('/^[A-Z]{3,8}$/',$currency))||($maxUses!==''&&(int)$maxUses<1))$error='اطلاعات کد تخفیف معتبر نیست.';else try{$pdo->prepare('INSERT INTO discounts(code,type,value,minimum_amount,currency,max_uses,starts_at,expires_at) VALUES(:code,:type,:value,:minimum,:currency,:max_uses,:starts,:expires)')->execute(['code'=>$code,'type'=>$type,'value'=>$value,'minimum'=>$minimum,'currency'=>$currency?:null,'max_uses'=>$maxUses===''?null:(int)$maxUses,'starts'=>$starts?:null,'expires'=>$expires?:null]);$id=(int)$pdo->lastInsertId();Audit::log('discount.created','کد تخفیف ساخته شد',(int)$user['id'],['discount_id'=>$id,'code'=>$code]);header('Location: /admin/discounts');return;}catch(Throwable){$error='کد تخفیف تکراری است یا تاریخ‌ها معتبر نیستند.';}
        }
        $discounts=$pdo->query('SELECT * FROM discounts ORDER BY id DESC LIMIT 300')->fetchAll();View::render('discounts',compact('user','discounts','error'));
    }
    public function taxes(): void
    {
        $user=Auth::requireUser(['owner','admin']);$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$action=(string)($_POST['action']??'save');$id=(int)($_POST['id']??0);
            if($action==='toggle'){$pdo->prepare('UPDATE tax_rates SET is_active=CASE WHEN is_active=1 THEN 0 ELSE 1 END,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$id]);Audit::log('tax.toggled','وضعیت نرخ مالیات تغییر کرد',(int)$user['id'],['tax_rate_id'=>$id]);header('Location: /admin/taxes');return;}
            $name=trim((string)($_POST['name']??''));$country=strtoupper(trim((string)($_POST['country']??'')));$currency=strtoupper(trim((string)($_POST['currency']??'')));$rate=round((float)($_POST['rate']??0),4);$priority=max(0,(int)($_POST['priority']??100));
            if(mb_strlen($name)<2||($country!==''&&!preg_match('/^[A-Z]{2}$/',$country))||($currency!==''&&!preg_match('/^[A-Z]{3,8}$/',$currency))||$rate<0||$rate>100)$error='نام، کشور، ارز یا نرخ مالیات معتبر نیست.';else try{$pdo->prepare('INSERT INTO tax_rates(name,country,currency,rate,priority) VALUES(:name,:country,:currency,:rate,:priority)')->execute(['name'=>$name,'country'=>$country?:null,'currency'=>$currency?:null,'rate'=>$rate,'priority'=>$priority]);$id=(int)$pdo->lastInsertId();Audit::log('tax.created','نرخ مالیات ساخته شد',(int)$user['id'],['tax_rate_id'=>$id,'rate'=>$rate]);header('Location: /admin/taxes');return;}catch(Throwable){$error='این ترکیب کشور و ارز قبلاً ثبت شده است.';}
        }
        $taxes=$pdo->query('SELECT * FROM tax_rates ORDER BY priority ASC,id DESC')->fetchAll();View::render('taxes',compact('user','taxes','error'));
    }
    public function services(): void
    {
        $user=$this->staff();$pdo=Database::connection();
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'');$cycle=(string)($_POST['billing_cycle']??'monthly');$price=round((float)($_POST['renewal_price']??0),2);$currency=strtoupper(trim((string)($_POST['currency']??'RUB')));if($id<1||!in_array($status,['pending','active','suspended','cancelled','expired'],true)||!in_array($cycle,['monthly','quarterly','yearly'],true)||$price<0||!preg_match('/^[A-Z]{3,8}$/',$currency))$this->deny();$pdo->prepare('UPDATE services SET status=:status,identifier=:identifier,expires_at=:expires,notes=:notes,auto_renew=:auto,billing_cycle=:cycle,renewal_price=:price,currency=:currency,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['status'=>$status,'identifier'=>trim((string)($_POST['identifier']??'')),'expires'=>trim((string)($_POST['expires_at']??''))?:null,'notes'=>trim((string)($_POST['notes']??'')),'auto'=>isset($_POST['auto_renew'])?1:0,'cycle'=>$cycle,'price'=>$price,'currency'=>$currency,'id'=>$id]);Audit::log('service.updated','سرویس مشتری ویرایش شد',(int)$user['id'],['service_id'=>$id,'status'=>$status]);header('Location: /admin/services');return;}
        $services=$pdo->query('SELECT s.*,u.name customer,u.email FROM services s JOIN users u ON u.id=s.user_id ORDER BY s.id DESC LIMIT 200')->fetchAll();View::render('services',compact('user','services'));
    }
    public function renewals(): void
    {
        $user=$this->staff();$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$serviceId=(int)($_POST['service_id']??0);$pdo->beginTransaction();try{
                $lock=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'?' FOR UPDATE':'';
                $s=$pdo->prepare('SELECT s.*,u.name customer FROM services s JOIN users u ON u.id=s.user_id WHERE s.id=:id'.$lock);$s->execute(['id'=>$serviceId]);$service=$s->fetch();
                if(!$service||!in_array($service['status'],['active','expired'],true)||!$service['expires_at']||(float)$service['renewal_price']<=0)throw new \RuntimeException('تنظیمات تمدید این سرویس کامل نیست.');
                $due=date('Y-m-d',strtotime((string)$service['expires_at']));$key=$serviceId.'-'.$due;
                $number='REN-'.gmdate('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));
                $quote=$this->taxQuote($pdo,(int)$service['user_id'],(float)$service['renewal_price'],(string)$service['currency']);
                $pdo->prepare("INSERT INTO invoices(invoice_number,user_id,subtotal,tax_rate_id,tax_rate,tax_amount,total,currency,status,due_at,created_by) VALUES(:num,:uid,:subtotal,:tax_id,:tax_rate,:tax_amount,:total,:currency,'unpaid',:due,:staff)")->execute(['num'=>$number,'uid'=>$service['user_id'],'subtotal'=>$quote['subtotal'],'tax_id'=>$quote['tax_id'],'tax_rate'=>$quote['tax_rate'],'tax_amount'=>$quote['tax_amount'],'total'=>$quote['total'],'currency'=>$service['currency'],'due'=>$due,'staff'=>$user['id']]);$invoiceId=(int)$pdo->lastInsertId();
                $pdo->prepare('INSERT INTO service_renewals(service_id,invoice_id,renewal_key,period_end,status,created_by) VALUES(:service,:invoice,:key,:due,\'invoiced\',:staff)')->execute(['service'=>$serviceId,'invoice'=>$invoiceId,'key'=>$key,'due'=>$due,'staff'=>$user['id']]);
                $pdo->commit();Audit::log('renewal.invoice_created','فاکتور تمدید سرویس ساخته شد',(int)$user['id'],['service_id'=>$serviceId,'invoice_id'=>$invoiceId]);header('Location: /admin/invoices/'.$invoiceId);return;
            }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof \RuntimeException?$e->getMessage():'فاکتور تمدید قبلاً ساخته شده یا عملیات ناموفق بود.';}
        }
        $days=max(0,min(365,(int)($_GET['days']??30)));$modifier=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='sqlite'?"datetime('now','+".$days." days')":"CURRENT_TIMESTAMP + INTERVAL '".$days." days'";
        $services=$pdo->query("SELECT s.*,u.name customer,u.email,r.invoice_id renewal_invoice_id FROM services s JOIN users u ON u.id=s.user_id LEFT JOIN service_renewals r ON r.service_id=s.id AND r.renewal_key=(CAST(s.id AS VARCHAR)||'-'||substr(CAST(s.expires_at AS VARCHAR),1,10)) WHERE s.status IN ('active','expired') AND s.expires_at IS NOT NULL AND s.expires_at <= $modifier ORDER BY s.expires_at ASC LIMIT 300")->fetchAll();
        View::render('renewals',compact('user','services','days','error'));
    }
    public function tickets(): void
    {
        $user=$this->staff();$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$uid=(int)($_POST['user_id']??0);$subject=trim((string)($_POST['subject']??''));$body=trim((string)($_POST['body']??''));$priority=(string)($_POST['priority']??'normal');if($uid<1||mb_strlen($subject)<3||mb_strlen($body)<2||!in_array($priority,['low','normal','high','urgent'],true))$error='اطلاعات تیکت کامل نیست.';else{$pdo->beginTransaction();try{$s=$pdo->prepare("INSERT INTO tickets(user_id,subject,priority,status,assigned_to) VALUES(:uid,:subject,:priority,'open',:staff)");$s->execute(['uid'=>$uid,'subject'=>$subject,'priority'=>$priority,'staff'=>$user['id']]);$tid=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO ticket_messages(ticket_id,author_id,body) VALUES(:ticket,:author,:body)')->execute(['ticket'=>$tid,'author'=>$user['id'],'body'=>$body]);$pdo->commit();Audit::log('ticket.created','تیکت جدید ساخته شد',(int)$user['id'],['ticket_id'=>$tid]);header('Location: /admin/tickets/'.$tid);return;}catch(Throwable $e){$pdo->rollBack();$error='ساخت تیکت انجام نشد.';}}}
        $status=(string)($_GET['status']??'');$priority=(string)($_GET['priority']??'');$where=[];$params=[];if(in_array($status,['open','answered','customer_reply','closed'],true)){$where[]='t.status=:status';$params['status']=$status;}if(in_array($priority,['low','normal','high','urgent'],true)){$where[]='t.priority=:priority';$params['priority']=$priority;}$sql=$where?' WHERE '.implode(' AND ',$where):'';$s=$pdo->prepare('SELECT t.*,u.name customer,a.name assignee FROM tickets t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN users a ON a.id=t.assigned_to'.$sql.' ORDER BY t.updated_at DESC LIMIT 200');$s->execute($params);$tickets=$s->fetchAll();$clients=$pdo->query("SELECT id,name,email FROM users WHERE role='client' AND status<>'closed' ORDER BY name")->fetchAll();View::render('tickets',compact('user','tickets','clients','error','status','priority'));
    }
    public function ticket(int $id): void
    {
        $user=$this->staff();$pdo=Database::connection();$s=$pdo->prepare('SELECT t.*,u.name customer,u.email,a.name assignee FROM tickets t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN users a ON a.id=t.assigned_to WHERE t.id=:id');$s->execute(['id'=>$id]);$ticket=$s->fetch();if(!$ticket)$this->missing();
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$action=(string)($_POST['action']??'reply');if($action==='update'){$status=(string)($_POST['status']??'');$priority=(string)($_POST['priority']??'');if(in_array($status,['open','answered','customer_reply','closed'],true)&&in_array($priority,['low','normal','high','urgent'],true)){$pdo->prepare('UPDATE tickets SET status=:status,priority=:priority,assigned_to=:assigned,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['status'=>$status,'priority'=>$priority,'assigned'=>$user['id'],'id'=>$id]);Audit::log('ticket.updated','وضعیت تیکت تغییر کرد',(int)$user['id'],['ticket_id'=>$id]);}}else{$body=trim((string)($_POST['body']??''));$internal=isset($_POST['internal'])?1:0;if($body!==''){$pdo->prepare('INSERT INTO ticket_messages(ticket_id,author_id,body,is_internal) VALUES(:ticket,:author,:body,:internal)')->execute(['ticket'=>$id,'author'=>$user['id'],'body'=>$body,'internal'=>$internal]);$pdo->prepare("UPDATE tickets SET status=:status,assigned_to=:assigned,updated_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['status'=>$internal?$ticket['status']:'answered','assigned'=>$user['id'],'id'=>$id]);Audit::log($internal?'ticket.internal_note':'ticket.replied',$internal?'یادداشت داخلی ثبت شد':'به تیکت پاسخ داده شد',(int)$user['id'],['ticket_id'=>$id]);}}header('Location: /admin/tickets/'.$id);return;}
        $m=$pdo->prepare('SELECT m.*,u.name author FROM ticket_messages m LEFT JOIN users u ON u.id=m.author_id WHERE m.ticket_id=:id ORDER BY m.id');$m->execute(['id'=>$id]);$messages=$m->fetchAll();View::render('ticket',compact('user','ticket','messages'));
    }
    public function invoices(): void
    {
        $user=$this->staff();$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$orderId=(int)($_POST['order_id']??0);$due=trim((string)($_POST['due_at']??''));
            $s=$pdo->prepare('SELECT id,user_id,order_number,amount,currency FROM orders WHERE id=:id');$s->execute(['id'=>$orderId]);$order=$s->fetch();
            if(!$order)$error='سفارش معتبر نیست.';else try{$number='INV-'.gmdate('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$quote=$this->taxQuote($pdo,(int)$order['user_id'],(float)$order['amount'],(string)$order['currency']);$pdo->prepare("INSERT INTO invoices(invoice_number,order_id,user_id,subtotal,tax_rate_id,tax_rate,tax_amount,total,currency,status,due_at,created_by) VALUES(:num,:oid,:uid,:subtotal,:tax_id,:tax_rate,:tax_amount,:total,:currency,'unpaid',:due,:staff)")->execute(['num'=>$number,'oid'=>$order['id'],'uid'=>$order['user_id'],'subtotal'=>$quote['subtotal'],'tax_id'=>$quote['tax_id'],'tax_rate'=>$quote['tax_rate'],'tax_amount'=>$quote['tax_amount'],'total'=>$quote['total'],'currency'=>$order['currency'],'due'=>$due?:null,'staff'=>$user['id']]);$id=(int)$pdo->lastInsertId();Audit::log('invoice.created','فاکتور ساخته شد',(int)$user['id'],['invoice_id'=>$id,'number'=>$number,'tax_amount'=>$quote['tax_amount']]);header('Location: /admin/invoices/'.$id);return;}catch(Throwable){$error='برای این سفارش قبلاً فاکتور ساخته شده است.';}
        }
        $status=(string)($_GET['status']??'');$where='';$params=[];if(in_array($status,['unpaid','partial','paid','cancelled','refunded'],true)){$where=' WHERE i.status=:status';$params['status']=$status;}$s=$pdo->prepare('SELECT i.*,u.name customer,COALESCE(SUM(p.amount),0) paid_amount FROM invoices i JOIN users u ON u.id=i.user_id LEFT JOIN payments p ON p.invoice_id=i.id AND p.status=\'confirmed\''.$where.' GROUP BY i.id,u.name ORDER BY i.id DESC LIMIT 200');$s->execute($params);$invoices=$s->fetchAll();$orders=$pdo->query("SELECT o.id,o.order_number,o.amount,o.currency,u.name customer FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN invoices i ON i.order_id=o.id WHERE i.id IS NULL AND o.status NOT IN ('cancelled','refunded') ORDER BY o.id DESC LIMIT 200")->fetchAll();View::render('invoices',compact('user','invoices','orders','error','status'));
    }
    public function invoice(int $id): void
    {
        $user=$this->staff();$pdo=Database::connection();$s=$pdo->prepare('SELECT i.*,u.name customer,u.email,o.order_number,COALESCE(SUM(p.amount) FILTER (WHERE p.status=\'confirmed\'),0) paid_amount FROM invoices i JOIN users u ON u.id=i.user_id LEFT JOIN orders o ON o.id=i.order_id LEFT JOIN payments p ON p.invoice_id=i.id WHERE i.id=:id GROUP BY i.id,u.name,u.email,o.order_number');$s->execute(['id'=>$id]);$invoice=$s->fetch();if(!$invoice)$this->missing();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$action=(string)($_POST['action']??'payment');if($action==='cancel'){if(!in_array($user['role'],['owner','admin'],true))$this->deny();$pdo->prepare("UPDATE invoices SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status<>'paid'")->execute(['id'=>$id]);Audit::log('invoice.cancelled','فاکتور لغو شد',(int)$user['id'],['invoice_id'=>$id]);}else{$amount=(float)($_POST['amount']??0);$balance=max(0,(float)$invoice['total']-(float)$invoice['paid_amount']);$method=trim((string)($_POST['method']??''));$reference=trim((string)($_POST['reference']??''));if($amount<=0||$amount>$balance||$balance<=0||mb_strlen($method)<2||in_array($invoice['status'],['cancelled','refunded'],true))$error='مبلغ یا روش پرداخت معتبر نیست.';else{$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO payments(invoice_id,user_id,amount,currency,method,reference,status,received_by) VALUES(:invoice,:uid,:amount,:currency,:method,:reference,'confirmed',:staff)")->execute(['invoice'=>$id,'uid'=>$invoice['user_id'],'amount'=>$amount,'currency'=>$invoice['currency'],'method'=>$method,'reference'=>$reference?:null,'staff'=>$user['id']]);$paid=(float)$invoice['paid_amount']+$amount;$status=$paid>=(float)$invoice['total']?'paid':'partial';$pdo->prepare('UPDATE invoices SET status=:status,paid_at=CASE WHEN :status2=\'paid\' THEN CURRENT_TIMESTAMP ELSE paid_at END,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['status'=>$status,'status2'=>$status,'id'=>$id]);if($status==='paid'&&$invoice['order_id'])$pdo->prepare("UPDATE orders SET status='paid',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='pending'")->execute(['id'=>$invoice['order_id']]);$pdo->commit();Audit::log('payment.recorded','پرداخت ثبت شد',(int)$user['id'],['invoice_id'=>$id,'amount'=>$amount,'currency'=>$invoice['currency']]);header('Location: /admin/invoices/'.$id);return;}catch(Throwable $e){$pdo->rollBack();throw $e;}}}if(!$error){header('Location: /admin/invoices/'.$id);return;}}
        $p=$pdo->prepare('SELECT p.*,u.name receiver FROM payments p LEFT JOIN users u ON u.id=p.received_by WHERE p.invoice_id=:id ORDER BY p.id DESC');$p->execute(['id'=>$id]);$payments=$p->fetchAll();View::render('invoice',compact('user','invoice','payments','error'));
    }
    public function finance(): void
    {
        $user=Auth::requireUser(['owner','admin']);$pdo=Database::connection();$summary=$pdo->query("SELECT currency,COALESCE(SUM(total),0) invoiced,COALESCE(SUM(CASE WHEN status='paid' THEN total ELSE 0 END),0) paid_invoices,COALESCE(SUM(CASE WHEN status IN ('unpaid','partial') THEN total ELSE 0 END),0) open_total FROM invoices WHERE status<>'cancelled' GROUP BY currency ORDER BY currency")->fetchAll();$payments=$pdo->query("SELECT p.*,i.invoice_number,u.name customer FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN users u ON u.id=p.user_id WHERE p.status='confirmed' ORDER BY p.id DESC LIMIT 100")->fetchAll();View::render('finance',compact('user','summary','payments'));
    }
    public function wallets(): void
    {
        $user=Auth::requireUser(['owner','admin']);$pdo=Database::connection();
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();$uid=(int)($_POST['user_id']??0);$newCurrency=strtoupper(trim((string)($_POST['currency']??'')));if($uid<1||!preg_match('/^[A-Z]{3,8}$/',$newCurrency))$this->deny();try{$pdo->prepare('INSERT INTO wallets(user_id,currency) VALUES(:uid,:currency)')->execute(['uid'=>$uid,'currency'=>$newCurrency]);$wid=(int)$pdo->lastInsertId();}catch(Throwable){$find=$pdo->prepare('SELECT id FROM wallets WHERE user_id=:uid AND currency=:currency');$find->execute(['uid'=>$uid,'currency'=>$newCurrency]);$wid=(int)$find->fetchColumn();}if($wid<1)$this->deny();Audit::log('wallet.created','کیف پول مشتری ساخته شد',(int)$user['id'],['wallet_id'=>$wid,'user_id'=>$uid,'currency'=>$newCurrency]);header('Location: /admin/wallets/'.$wid);return;}
        $currency=strtoupper(trim((string)($_GET['currency']??'')));$params=[];$where='';
        if($currency!==''&&preg_match('/^[A-Z]{3,8}$/',$currency)){$where=' WHERE w.currency=:currency';$params['currency']=$currency;}
        $s=$pdo->prepare("SELECT w.id,w.user_id,w.currency,w.balance,w.updated_at,u.name customer,u.email FROM wallets w JOIN users u ON u.id=w.user_id$where ORDER BY w.updated_at DESC,w.id DESC LIMIT 300");$s->execute($params);$wallets=$s->fetchAll();
        $clients=$pdo->query("SELECT id,name,email FROM users WHERE role='client' AND status<>'closed' ORDER BY name")->fetchAll();
        $totals=$pdo->query('SELECT currency,COALESCE(SUM(balance),0) balance FROM wallets GROUP BY currency ORDER BY currency')->fetchAll();
        View::render('wallets',compact('user','wallets','clients','totals','currency'));
    }
    public function wallet(int $id): void
    {
        $user=Auth::requireUser(['owner','admin']);$pdo=Database::connection();$error=null;
        $s=$pdo->prepare('SELECT w.*,u.name customer,u.email FROM wallets w JOIN users u ON u.id=w.user_id WHERE w.id=:id');$s->execute(['id'=>$id]);$wallet=$s->fetch();if(!$wallet)$this->missing();
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$action=(string)($_POST['action']??'adjust');
            if($action==='pay_invoice'){$invoiceId=(int)($_POST['invoice_id']??0);$pdo->beginTransaction();try{
                $lock=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'?' FOR UPDATE':'';
                $ws=$pdo->prepare('SELECT * FROM wallets WHERE id=:id'.$lock);$ws->execute(['id'=>$id]);$current=$ws->fetch();
                $is=$pdo->prepare('SELECT * FROM invoices WHERE id=:iid AND user_id=:uid'.$lock);$is->execute(['iid'=>$invoiceId,'uid'=>$wallet['user_id']]);$invoice=$is->fetch();
                if($invoice){$ps=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM payments WHERE invoice_id=:id AND status='confirmed'");$ps->execute(['id'=>$invoiceId]);$invoice['paid_amount']=$ps->fetchColumn();}
                $due=$invoice?round((float)$invoice['total']-(float)$invoice['paid_amount'],2):0.0;
                if(!$invoice||$invoice['currency']!==$current['currency']||$due<=0||in_array($invoice['status'],['paid','cancelled','refunded'],true)||round((float)$current['balance'],2)<$due)throw new \RuntimeException('موجودی یا فاکتور برای پرداخت معتبر نیست.');
                $reference='WALLET-'.$id.'-'.strtoupper(bin2hex(random_bytes(4)));
                $pdo->prepare('UPDATE wallets SET balance=balance-:amount,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['amount'=>$due,'id'=>$id]);
                $pdo->prepare("INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,currency,reference,description,created_by) VALUES(:wallet,:uid,'debit',:amount,:balance,:currency,:reference,:description,:staff)")->execute(['wallet'=>$id,'uid'=>$wallet['user_id'],'amount'=>$due,'balance'=>round((float)$current['balance']-$due,2),'currency'=>$current['currency'],'reference'=>$reference,'description'=>'پرداخت فاکتور '.$invoice['invoice_number'],'staff'=>$user['id']]);
                $pdo->prepare("INSERT INTO payments(invoice_id,user_id,amount,currency,method,reference,status,received_by) VALUES(:invoice,:uid,:amount,:currency,'wallet',:reference,'confirmed',:staff)")->execute(['invoice'=>$invoiceId,'uid'=>$wallet['user_id'],'amount'=>$due,'currency'=>$current['currency'],'reference'=>$reference,'staff'=>$user['id']]);
                $pdo->prepare("UPDATE invoices SET status='paid',paid_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['id'=>$invoiceId]);if($invoice['order_id'])$pdo->prepare("UPDATE orders SET status='paid',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='pending'")->execute(['id'=>$invoice['order_id']]);
                $pdo->commit();Audit::log('wallet.invoice_paid','فاکتور از کیف پول پرداخت شد',(int)$user['id'],['wallet_id'=>$id,'invoice_id'=>$invoiceId,'amount'=>$due,'currency'=>$current['currency']]);header('Location: /admin/wallets/'.$id);return;
            }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof \RuntimeException?$e->getMessage():'پرداخت انجام نشد.';}}
            else{$kind=(string)($_POST['kind']??'credit');$amount=round((float)($_POST['amount']??0),2);$description=trim((string)($_POST['description']??''));$reference=trim((string)($_POST['reference']??''));if(!in_array($kind,['credit','debit'],true)||$amount<=0||mb_strlen($description)<2)$error='مبلغ و توضیح معتبر لازم است.';else{$pdo->beginTransaction();try{$lock=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME)==='pgsql'?' FOR UPDATE':'';$ws=$pdo->prepare('SELECT balance FROM wallets WHERE id=:id'.$lock);$ws->execute(['id'=>$id]);$before=(float)$ws->fetchColumn();$after=round($before+($kind==='credit'?$amount:-$amount),2);if($after<0)throw new \RuntimeException('موجودی کیف پول کافی نیست.');$pdo->prepare('UPDATE wallets SET balance=:balance,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['balance'=>$after,'id'=>$id]);$pdo->prepare('INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,currency,reference,description,created_by) VALUES(:wallet,:uid,:type,:amount,:balance,:currency,:reference,:description,:staff)')->execute(['wallet'=>$id,'uid'=>$wallet['user_id'],'type'=>$kind,'amount'=>$amount,'balance'=>$after,'currency'=>$wallet['currency'],'reference'=>$reference?:null,'description'=>$description,'staff'=>$user['id']]);$pdo->commit();Audit::log('wallet.adjusted','موجودی کیف پول اصلاح شد',(int)$user['id'],['wallet_id'=>$id,'type'=>$kind,'amount'=>$amount,'currency'=>$wallet['currency']]);header('Location: /admin/wallets/'.$id);return;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof \RuntimeException?$e->getMessage():'تراکنش ثبت نشد.';}}}
        }
        $t=$pdo->prepare('SELECT wt.*,u.name staff_name FROM wallet_transactions wt LEFT JOIN users u ON u.id=wt.created_by WHERE wt.wallet_id=:id ORDER BY wt.id DESC LIMIT 200');$t->execute(['id'=>$id]);$transactions=$t->fetchAll();
        $i=$pdo->prepare("SELECT i.id,i.invoice_number,i.total,i.currency,i.status,COALESCE(SUM(CASE WHEN p.status='confirmed' THEN p.amount ELSE 0 END),0) paid_amount FROM invoices i LEFT JOIN payments p ON p.invoice_id=i.id WHERE i.user_id=:uid AND i.currency=:currency AND i.status IN ('unpaid','partial') GROUP BY i.id ORDER BY i.id DESC");$i->execute(['uid'=>$wallet['user_id'],'currency'=>$wallet['currency']]);$invoices=$i->fetchAll();
        View::render('wallet',compact('user','wallet','transactions','invoices','error'));
    }
    public function notifications(): void
    {
        $user=$this->staff();$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$action=(string)($_POST['action']??'');
            if($action==='generate'){
                $days=max(0,min(90,(int)($_POST['days']??7)));$limit=date('Y-m-d 23:59:59',strtotime('+'.$days.' days'));$created=0;
                $s=$pdo->prepare("SELECT i.id,i.invoice_number,i.user_id,i.total,i.currency,i.due_at,u.name FROM invoices i JOIN users u ON u.id=i.user_id WHERE i.status IN ('unpaid','partial') AND i.due_at IS NOT NULL AND i.due_at<=:lim");$s->execute(['lim'=>$limit]);
                foreach($s->fetchAll() as $row){$key='invoice-due-'.$row['id'].'-'.substr((string)$row['due_at'],0,10);try{$pdo->prepare("INSERT INTO notifications(user_id,channel,event_type,dedupe_key,subject,body,created_by) VALUES(:uid,'email','invoice_due',:key,:subject,:body,:staff)")->execute(['uid'=>$row['user_id'],'key'=>$key,'subject'=>'یادآوری فاکتور '.$row['invoice_number'],'body'=>'فاکتور '.$row['invoice_number'].' به مبلغ '.$row['total'].' '.$row['currency'].' سررسید شده یا نزدیک سررسید است.','staff'=>$user['id']]);$created++;}catch(Throwable){}}
                $s=$pdo->prepare("SELECT s.id,s.name,s.user_id,s.expires_at,u.name customer FROM services s JOIN users u ON u.id=s.user_id WHERE s.status='active' AND s.expires_at IS NOT NULL AND s.expires_at<=:lim");$s->execute(['lim'=>$limit]);
                foreach($s->fetchAll() as $row){$key='service-expiry-'.$row['id'].'-'.substr((string)$row['expires_at'],0,10);try{$pdo->prepare("INSERT INTO notifications(user_id,channel,event_type,dedupe_key,subject,body,created_by) VALUES(:uid,'email','service_expiry',:key,:subject,:body,:staff)")->execute(['uid'=>$row['user_id'],'key'=>$key,'subject'=>'یادآوری تمدید '.$row['name'],'body'=>'سرویس '.$row['name'].' در تاریخ '.substr((string)$row['expires_at'],0,10).' منقضی می‌شود.','staff'=>$user['id']]);$created++;}catch(Throwable){}}
                Audit::log('notifications.generated','اعلان‌های سررسید ساخته شد',(int)$user['id'],['created'=>$created,'days'=>$days]);header('Location: /admin/notifications');return;
            }
            if($action==='create'){$uid=(int)($_POST['user_id']??0);$subject=trim((string)($_POST['subject']??''));$body=trim((string)($_POST['body']??''));if($uid<1||mb_strlen($subject)<3||mb_strlen($body)<2)$error='مشتری، عنوان و متن معتبر لازم است.';else{$key='manual-'.$uid.'-'.bin2hex(random_bytes(8));$pdo->prepare("INSERT INTO notifications(user_id,channel,event_type,dedupe_key,subject,body,created_by) VALUES(:uid,'email','manual',:key,:subject,:body,:staff)")->execute(['uid'=>$uid,'key'=>$key,'subject'=>$subject,'body'=>$body,'staff'=>$user['id']]);Audit::log('notification.created','اعلان دستی ساخته شد',(int)$user['id'],['user_id'=>$uid]);header('Location: /admin/notifications');return;}}
            if($action==='mark'){$id=(int)($_POST['id']??0);$result=(string)($_POST['result']??'');if($id<1||!in_array($result,['sent','cancelled'],true))$this->deny();$sql=$result==='sent'?"UPDATE notifications SET status='sent',sent_at=CURRENT_TIMESTAMP,attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='pending'":"UPDATE notifications SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=:id AND status='pending'";$pdo->prepare($sql)->execute(['id'=>$id]);Audit::log('notification.status_changed','وضعیت اعلان تغییر کرد',(int)$user['id'],['notification_id'=>$id,'status'=>$result]);header('Location: /admin/notifications');return;}
        }
        $status=(string)($_GET['status']??'');$where='';$params=[];if(in_array($status,['pending','sent','failed','cancelled'],true)){$where=' WHERE n.status=:status';$params['status']=$status;}$s=$pdo->prepare('SELECT n.*,u.name customer,u.email FROM notifications n JOIN users u ON u.id=n.user_id'.$where.' ORDER BY n.scheduled_at DESC,n.id DESC LIMIT 300');$s->execute($params);$notifications=$s->fetchAll();$clients=$pdo->query("SELECT id,name,email FROM users WHERE role='client' AND status<>'closed' ORDER BY name")->fetchAll();View::render('notifications',compact('user','notifications','clients','status','error'));
    }
    public function audit():void{$user=Auth::requireUser(['owner','admin']);$events=Database::connection()->query('SELECT id,user_id,action,description,ip_address,created_at FROM audit_logs ORDER BY id DESC LIMIT 200')->fetchAll();View::render('audit',compact('user','events'));}
    public function system():void{$user=Auth::requireUser(['owner','admin']);$pdo=Database::connection();$products=$pdo->query('SELECT slug,name,type,status,current_version FROM products ORDER BY id')->fetchAll();$details=['version'=>\VazinCMS\Version::current(),'php'=>PHP_VERSION,'database'=>$pdo->getAttribute(PDO::ATTR_DRIVER_NAME),'environment'=>getenv('APP_ENV')?:'production'];View::render('system',compact('user','products','details'));}
    public function integrations(): void
    {
        $user=Auth::requireUser(['owner']);$pdo=Database::connection();$error=null;$newToken=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$action=(string)($_POST['action']??'create');
            if($action==='revoke'){$id=(int)($_POST['id']??0);$pdo->prepare('UPDATE api_tokens SET revoked_at=CURRENT_TIMESTAMP WHERE id=:id AND revoked_at IS NULL')->execute(['id'=>$id]);Audit::log('api_token.revoked','کلید اتصال لغو شد',(int)$user['id'],['token_id'=>$id]);header('Location: /admin/integrations');return;}
            $name=trim((string)($_POST['name']??''));$scopes=array_values(array_intersect((array)($_POST['scopes']??[]),['read','billing','wallet','services','modules','customers','orders','content']));$expires=trim((string)($_POST['expires_at']??''));
            if($expires!==''&&strtotime($expires)===false)$error='تاریخ انقضا معتبر نیست.';elseif(mb_strlen($name)<3||$scopes===[])$error='نام و حداقل یک دسترسی معتبر لازم است.';else{$secret='vo_live_'.bin2hex(random_bytes(24));$prefix=substr($secret,0,16);$stmt=$pdo->prepare('INSERT INTO api_tokens(name,token_prefix,token_hash,scopes,expires_at,created_by) VALUES(:name,:prefix,:hash,:scopes,:expires,:uid)');$stmt->execute(['name'=>$name,'prefix'=>$prefix,'hash'=>hash('sha256',$secret),'scopes'=>json_encode($scopes,JSON_UNESCAPED_SLASHES),'expires'=>$expires!==''?date('Y-m-d H:i:s',strtotime($expires)):null,'uid'=>$user['id']]);$id=(int)$pdo->lastInsertId();Audit::log('api_token.created','کلید اتصال ساخته شد',(int)$user['id'],['token_id'=>$id,'name'=>$name,'scopes'=>$scopes]);$newToken=$secret;}
        }
        $tokens=$pdo->query('SELECT id,name,token_prefix,scopes,last_used_at,expires_at,revoked_at,created_at FROM api_tokens ORDER BY id DESC')->fetchAll();$logs=$pdo->query('SELECT l.*,t.name token_name,t.token_prefix FROM api_request_logs l LEFT JOIN api_tokens t ON t.id=l.token_id ORDER BY l.id DESC LIMIT 100')->fetchAll();View::render('integrations',compact('user','tokens','logs','error','newToken'));
    }
    public function modules(): void
    {
        $user=Auth::requireUser(['owner']);$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){Security::verifyCsrf();try{$id=\VazinCMS\ModuleRegistry::save($_POST,(int)$user['id']);Audit::log('module.saved','ماژول یکپارچه ذخیره شد',(int)$user['id'],['module_id'=>$id]);header('Location: /admin/modules');return;}catch(Throwable $e){$error=$e->getMessage();}}
        $modules=\VazinCMS\ModuleRegistry::all();View::render('modules',compact('user','modules','error'));
    }
    public function webhooks(): void
    {
        $user=Auth::requireUser(['owner']);$pdo=Database::connection();$error=null;$newSecret=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$action=(string)($_POST['action']??'create');$id=(int)($_POST['id']??0);
            if($action==='toggle'){$pdo->prepare('UPDATE webhook_endpoints SET is_active=CASE WHEN is_active=1 THEN 0 ELSE 1 END,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$id]);Audit::log('webhook.toggled','وضعیت Webhook تغییر کرد',(int)$user['id'],['webhook_id'=>$id]);header('Location: /admin/webhooks');return;}
            if($action==='retry'){$delivery=(int)($_POST['delivery_id']??0);try{Webhook::retry($delivery);Audit::log('webhook.retried','ارسال Webhook دوباره در صف قرار گرفت',(int)$user['id'],['delivery_id'=>$delivery]);}catch(Throwable $e){$error=$e->getMessage();}if(!$error){header('Location: /admin/webhooks');return;}}
            if($action==='test'){try{Webhook::enqueue('webhook.test',['message'=>'Vazin Online webhook test','created_at'=>gmdate('c')],$id?:null);Audit::log('webhook.test_queued','Webhook آزمایشی در صف قرار گرفت',(int)$user['id'],['webhook_id'=>$id]);header('Location: /admin/webhooks');return;}catch(Throwable $e){$error=$e->getMessage();}}
            if($action==='create'){$name=trim((string)($_POST['name']??''));$url=trim((string)($_POST['url']??''));$events=array_values(array_intersect((array)($_POST['events']??[]),Webhook::events()));
                if(mb_strlen($name)<3||$events===[])$error='نام و حداقل یک رویداد معتبر لازم است.';else try{Webhook::validateUrl($url);$secret='whsec_'.bin2hex(random_bytes(24));$s=$pdo->prepare('INSERT INTO webhook_endpoints(name,url,secret_hash,secret_encrypted,events,created_by) VALUES(:name,:url,:hash,:secret,:events,:uid)');$s->execute(['name'=>$name,'url'=>$url,'hash'=>hash('sha256',$secret),'secret'=>Webhook::protect($secret),'events'=>json_encode($events,JSON_UNESCAPED_SLASHES),'uid'=>$user['id']]);$newSecret=$secret;Audit::log('webhook.created','مقصد Webhook ساخته شد',(int)$user['id'],['webhook_id'=>$pdo->lastInsertId(),'name'=>$name,'events'=>$events]);}catch(Throwable $e){$error=$e->getMessage();}}
        }
        $endpoints=$pdo->query('SELECT id,name,url,events,is_active,last_success_at,last_failure_at,created_at FROM webhook_endpoints ORDER BY id DESC')->fetchAll();$deliveries=$pdo->query('SELECT d.*,e.name endpoint_name FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id=d.endpoint_id ORDER BY d.id DESC LIMIT 150')->fetchAll();$externalDeliveryEnabled=DeliveryPolicy::externalEnabled();View::render('webhooks',compact('user','endpoints','deliveries','error','newSecret','externalDeliveryEnabled'));
    }
    public function scheduler(): void
    {
        $user=Auth::requireUser(['owner']);$pdo=Database::connection();$error=null;
        if($_SERVER['REQUEST_METHOD']==='POST'){
            Security::verifyCsrf();$action=(string)($_POST['action']??'create');$id=(int)($_POST['id']??0);
            if($action==='toggle'){$pdo->prepare('UPDATE scheduled_tasks SET is_active=CASE WHEN is_active=1 THEN 0 ELSE 1 END,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$id]);Audit::log('scheduler.toggled','وضعیت وظیفه زمان‌بندی تغییر کرد',(int)$user['id'],['task_id'=>$id]);header('Location: /admin/scheduler');return;}
            if($action==='run'){try{$result=Scheduler::runDue($id);Audit::log('scheduler.manual_run','وظیفه زمان‌بندی دستی اجرا شد',(int)$user['id'],['task_id'=>$id,'result'=>$result]);}catch(Throwable $e){$error=$e->getMessage();}if(!$error){header('Location: /admin/scheduler');return;}}
            if($action==='create'){$name=trim((string)($_POST['name']??''));$type=(string)($_POST['task_type']??'');$minutes=(int)($_POST['interval_minutes']??60);$retention=max(30,min(3650,(int)($_POST['retention_days']??365)));
                if(mb_strlen($name)<3||!array_key_exists($type,Scheduler::types())||$minutes<1||$minutes>525600)$error='اطلاعات وظیفه معتبر نیست.';else{$config=$type==='audit_cleanup'?['retention_days'=>$retention]:[];$s=$pdo->prepare('INSERT INTO scheduled_tasks(name,task_type,interval_minutes,config,created_by) VALUES(:name,:type,:minutes,:config,:uid)');$s->execute(['name'=>$name,'type'=>$type,'minutes'=>$minutes,'config'=>json_encode($config,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'uid'=>$user['id']]);Audit::log('scheduler.created','وظیفه زمان‌بندی ساخته شد',(int)$user['id'],['task_id'=>$pdo->lastInsertId(),'type'=>$type,'interval_minutes'=>$minutes]);header('Location: /admin/scheduler');return;}
            }
        }
        $tasks=$pdo->query('SELECT * FROM scheduled_tasks ORDER BY id DESC')->fetchAll();$activeCount=count(array_filter($tasks,static fn(array $t):bool=>(bool)$t['is_active']));$runs=$pdo->query('SELECT r.*,t.name task_name FROM scheduled_task_runs r JOIN scheduled_tasks t ON t.id=r.task_id ORDER BY r.id DESC LIMIT 150')->fetchAll();View::render('scheduler',compact('user','tasks','runs','activeCount','error'));
    }
    private function taxQuote(PDO $pdo,int $userId,float $subtotal,string $currency):array
    {
        $country='';$s=$pdo->prepare('SELECT country FROM users WHERE id=:id');$s->execute(['id'=>$userId]);$country=strtoupper(trim((string)$s->fetchColumn()));
        $q=$pdo->prepare("SELECT id,rate FROM tax_rates WHERE is_active=1 AND (country IS NULL OR country='' OR country=:country) AND (currency IS NULL OR currency='' OR currency=:currency) ORDER BY CASE WHEN country=:country2 THEN 0 ELSE 1 END,CASE WHEN currency=:currency2 THEN 0 ELSE 1 END,priority ASC,id DESC LIMIT 1");
        $q->execute(['country'=>$country,'currency'=>$currency,'country2'=>$country,'currency2'=>$currency]);$tax=$q->fetch();$rate=$tax?round((float)$tax['rate'],4):0.0;$base=round($subtotal,2);$amount=round($base*$rate/100,2);
        return ['subtotal'=>$base,'tax_id'=>$tax?(int)$tax['id']:null,'tax_rate'=>$rate,'tax_amount'=>$amount,'total'=>round($base+$amount,2)];
    }
    private function deny():never{http_response_code(403);View::render('error',['title'=>'دسترسی غیرمجاز','message'=>'اجازه انجام این کار را ندارید.']);exit;}
    private function missing():never{http_response_code(404);View::render('error',['title'=>'پیدا نشد','message'=>'رکورد درخواستی وجود ندارد.']);exit;}
}
