ALTER TABLE services ADD COLUMN IF NOT EXISTS auto_renew SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(20) NOT NULL DEFAULT 'monthly';
ALTER TABLE services ADD COLUMN IF NOT EXISTS renewal_price NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS currency VARCHAR(8) NOT NULL DEFAULT 'RUB';
CREATE TABLE IF NOT EXISTS service_renewals (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
 invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT, renewal_key VARCHAR(100) NOT NULL UNIQUE,
 period_end DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'invoiced', created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_service_renewals_service ON service_renewals(service_id,created_at DESC);
INSERT INTO schema_migrations(version) VALUES('0.6.0') ON CONFLICT(version) DO NOTHING;
