CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 channel VARCHAR(20) NOT NULL DEFAULT 'email',
 event_type VARCHAR(50) NOT NULL,
 dedupe_key VARCHAR(160) NOT NULL UNIQUE,
 subject VARCHAR(200) NOT NULL,
 body TEXT NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'pending',
 scheduled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 sent_at TIMESTAMP NULL,
 failed_at TIMESTAMP NULL,
 attempts INTEGER NOT NULL DEFAULT 0,
 last_error TEXT NULL,
 created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_notifications_queue ON notifications(status,scheduled_at,id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,created_at DESC);
INSERT INTO schema_migrations(version) VALUES('0.7.0') ON CONFLICT(version) DO NOTHING;
