CREATE TABLE IF NOT EXISTS tax_rates (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 name VARCHAR(120) NOT NULL, country VARCHAR(2) NULL, currency VARCHAR(8) NULL,
 rate NUMERIC(7,4) NOT NULL CHECK(rate>=0 AND rate<=100), priority INTEGER NOT NULL DEFAULT 100,
 is_active SMALLINT NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(country,currency)
);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_rate_id BIGINT REFERENCES tax_rates(id);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_tax_rates_match ON tax_rates(is_active,country,currency,priority);
INSERT INTO schema_migrations(version) VALUES('0.9.0') ON CONFLICT(version) DO NOTHING;
