ALTER TABLE users ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS staff_permissions (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 permission VARCHAR(60) NOT NULL,
 is_granted SMALLINT NOT NULL DEFAULT 1,
 updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(user_id,permission)
);
CREATE TABLE IF NOT EXISTS active_sessions (
 id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 session_hash VARCHAR(64) NOT NULL UNIQUE,
 ip_address VARCHAR(64), user_agent VARCHAR(500),
 last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 revoked_at TIMESTAMP NULL
);
CREATE INDEX IF NOT EXISTS idx_active_sessions_user ON active_sessions(user_id,last_seen_at DESC);
INSERT INTO schema_migrations(version) VALUES('1.5.0') ON CONFLICT DO NOTHING;
