ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS block_schema_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS block_document TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_page_revisions ADD COLUMN IF NOT EXISTS block_schema_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cms_page_revisions ADD COLUMN IF NOT EXISTS block_document TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_autosaves ADD COLUMN IF NOT EXISTS block_schema_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cms_autosaves ADD COLUMN IF NOT EXISTS block_document TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS cms_reusable_blocks(id BIGSERIAL PRIMARY KEY,block_key VARCHAR(120) NOT NULL UNIQUE,label VARCHAR(255) NOT NULL,block_document TEXT NOT NULL,block_schema_version INTEGER NOT NULL DEFAULT 1,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cms_block_patterns(id BIGSERIAL PRIMARY KEY,pattern_key VARCHAR(120) NOT NULL UNIQUE,label VARCHAR(255) NOT NULL,category VARCHAR(120) NOT NULL DEFAULT 'general',block_document TEXT NOT NULL,block_schema_version INTEGER NOT NULL DEFAULT 1,is_system BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO schema_migrations(version) VALUES('10.12.0') ON CONFLICT(version) DO NOTHING;