ALTER TABLE cms_pages ADD COLUMN block_schema_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cms_pages ADD COLUMN block_document TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_page_revisions ADD COLUMN block_schema_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cms_page_revisions ADD COLUMN block_document TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_autosaves ADD COLUMN block_schema_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cms_autosaves ADD COLUMN block_document TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS cms_reusable_blocks(id INTEGER PRIMARY KEY AUTOINCREMENT,block_key TEXT NOT NULL UNIQUE,label TEXT NOT NULL,block_document TEXT NOT NULL,block_schema_version INTEGER NOT NULL DEFAULT 1,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cms_block_patterns(id INTEGER PRIMARY KEY AUTOINCREMENT,pattern_key TEXT NOT NULL UNIQUE,label TEXT NOT NULL,category TEXT NOT NULL DEFAULT 'general',block_document TEXT NOT NULL,block_schema_version INTEGER NOT NULL DEFAULT 1,is_system INTEGER NOT NULL DEFAULT 0 CHECK(is_system IN(0,1)),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO schema_migrations(version) VALUES('10.12.0');