CREATE TABLE IF NOT EXISTS cms_menu_items (id BIGSERIAL PRIMARY KEY,locale VARCHAR(12) NOT NULL DEFAULT 'fa',label VARCHAR(190) NOT NULL,url VARCHAR(500) NOT NULL,position INTEGER NOT NULL DEFAULT 0,is_enabled SMALLINT NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_cms_menu_locale_position ON cms_menu_items(locale,position,id);
INSERT INTO schema_migrations(version) VALUES('4.2.0') ON CONFLICT(version) DO NOTHING;
