CREATE TABLE IF NOT EXISTS cms_menu_items (id INTEGER PRIMARY KEY AUTOINCREMENT,locale TEXT NOT NULL DEFAULT 'fa',label TEXT NOT NULL,url TEXT NOT NULL,position INTEGER NOT NULL DEFAULT 0,is_enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_cms_menu_locale_position ON cms_menu_items(locale,position,id);
INSERT OR IGNORE INTO schema_migrations(version) VALUES('4.2.0');
