ALTER TABLE users ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS active_sessions (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,session_hash CHAR(64) NOT NULL UNIQUE,ip_address VARCHAR(64),user_agent TEXT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,revoked_at TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_active_sessions_user ON active_sessions(user_id,last_seen_at DESC);
CREATE TABLE IF NOT EXISTS login_attempts (id BIGSERIAL PRIMARY KEY,attempt_key CHAR(64) NOT NULL,email VARCHAR(190) NOT NULL,ip_address VARCHAR(64),succeeded SMALLINT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_login_limit ON login_attempts(attempt_key,created_at DESC);
INSERT INTO schema_migrations(version) VALUES('5.1.3') ON CONFLICT(version) DO NOTHING;
