ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS meta_title VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS meta_description TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS canonical_url VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS featured_image VARCHAR(500) NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS cms_page_revisions (id BIGSERIAL PRIMARY KEY,page_id BIGINT NOT NULL REFERENCES cms_pages(id) ON DELETE CASCADE,title VARCHAR(255) NOT NULL,body TEXT NOT NULL,meta_title VARCHAR(255) NOT NULL DEFAULT '',meta_description TEXT NOT NULL DEFAULT '',created_by BIGINT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_cms_revisions_page ON cms_page_revisions(page_id,id DESC);
CREATE TABLE IF NOT EXISTS cms_media (id BIGSERIAL PRIMARY KEY,file_name VARCHAR(255) NOT NULL,stored_name VARCHAR(255) NOT NULL UNIQUE,mime_type VARCHAR(100) NOT NULL,file_size BIGINT NOT NULL DEFAULT 0,alt_text VARCHAR(255) NOT NULL DEFAULT '',uploaded_by BIGINT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE cms_menu_items ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES cms_menu_items(id) ON DELETE SET NULL;
INSERT INTO schema_migrations(version) VALUES('6.0.0') ON CONFLICT DO NOTHING;
