ALTER TABLE cms_pages ADD COLUMN meta_title TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_pages ADD COLUMN meta_description TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_pages ADD COLUMN canonical_url TEXT NOT NULL DEFAULT '';
ALTER TABLE cms_pages ADD COLUMN featured_image TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS cms_page_revisions (id INTEGER PRIMARY KEY AUTOINCREMENT,page_id INTEGER NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,meta_title TEXT NOT NULL DEFAULT '',meta_description TEXT NOT NULL DEFAULT '',created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(page_id) REFERENCES cms_pages(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_cms_revisions_page ON cms_page_revisions(page_id,id DESC);
CREATE TABLE IF NOT EXISTS cms_media (id INTEGER PRIMARY KEY AUTOINCREMENT,file_name TEXT NOT NULL,stored_name TEXT NOT NULL UNIQUE,mime_type TEXT NOT NULL,file_size INTEGER NOT NULL DEFAULT 0,alt_text TEXT NOT NULL DEFAULT '',uploaded_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE cms_menu_items ADD COLUMN parent_id INTEGER;
INSERT INTO schema_migrations(version) VALUES('6.0.0');
