<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php';
use VazinCMS\{Database,DeliveryPolicy,Webhook};
if (!DeliveryPolicy::externalEnabled()) { echo "{\"ok\":true,\"status\":\"external_delivery_disabled\",\"processed\":0}\n"; exit(0); }
$pdo=Database::connection();$limit=max(1,min(100,(int)($argv[1]??25)));$driver=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME);$lock=$driver==='pgsql'?' FOR UPDATE SKIP LOCKED':'';
for($i=0;$i<$limit;$i++){
    $pdo->beginTransaction();
    try{$q=$pdo->query("SELECT d.*,e.url,e.secret_encrypted FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id=d.endpoint_id WHERE e.is_active=1 AND d.status IN ('pending','failed') AND (d.next_attempt_at IS NULL OR d.next_attempt_at<=CURRENT_TIMESTAMP) ORDER BY d.id LIMIT 1".$lock);$job=$q->fetch();if(!$job){$pdo->commit();break;}$pdo->prepare("UPDATE webhook_deliveries SET status='processing',attempt_count=attempt_count+1,updated_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['id'=>$job['id']]);$pdo->commit();
        Webhook::validateUrl((string)$job['url']);$timestamp=time();$payload=(string)$job['payload'];$signature=Webhook::signature($payload,Webhook::reveal((string)$job['secret_encrypted']),$timestamp);
        $headers=['Content-Type: application/json','User-Agent: VazinCMS-Webhook/1.2','X-Vazin-Event: '.$job['event_type'],'X-Vazin-Event-Id: '.$job['event_id'],'X-Vazin-Signature: '.$signature];
        $context=stream_context_create(['http'=>['method'=>'POST','header'=>implode("\r\n",$headers),'content'=>$payload,'timeout'=>15,'ignore_errors'=>true,'follow_location'=>0,'max_redirects'=>0],'ssl'=>['verify_peer'=>true,'verify_peer_name'=>true]]);$body=@file_get_contents((string)$job['url'],false,$context);$status=0;foreach($http_response_header??[] as $line){if(preg_match('#^HTTP/\S+\s+(\d{3})#',$line,$m)){$status=(int)$m[1];break;}}$ok=$status>=200&&$status<300;
        if($ok){$pdo->prepare("UPDATE webhook_deliveries SET status='delivered',response_status=:status,response_body=:body,last_error=NULL,delivered_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['status'=>$status,'body'=>mb_substr((string)$body,0,2000),'id'=>$job['id']]);$pdo->prepare('UPDATE webhook_endpoints SET last_success_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$job['endpoint_id']]);}
        else{$attempt=(int)$job['attempt_count']+1;$dead=$attempt>=5;$delay=min(3600,60*(2**max(0,$attempt-1)));$next=date('Y-m-d H:i:s',time()+$delay);$pdo->prepare("UPDATE webhook_deliveries SET status=:state,response_status=:status,response_body=:body,last_error=:error,next_attempt_at=:next,updated_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['state'=>$dead?'dead':'failed','status'=>$status?:null,'body'=>mb_substr((string)$body,0,2000),'error'=>'HTTP '.($status?:'connection error'),'next'=>$dead?null:$next,'id'=>$job['id']]);$pdo->prepare('UPDATE webhook_endpoints SET last_failure_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute(['id'=>$job['endpoint_id']]);}
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();if(isset($job['id'])){$pdo->prepare("UPDATE webhook_deliveries SET status='failed',last_error=:error,next_attempt_at=:next,updated_at=CURRENT_TIMESTAMP WHERE id=:id")->execute(['error'=>mb_substr($e->getMessage(),0,1000),'next'=>date('Y-m-d H:i:s',time()+300),'id'=>$job['id']]);}fwrite(STDERR,$e->getMessage()."\n");}
}
