#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
PYTHON_BIN="${PYTHON_BIN:-python3}"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([+-][0-9A-Za-z.-]+)?$ ]]
# The source tree may be checked out under any directory name in CI or by a
# contributor. Deployment path validation belongs to deploy/install.sh; the
# portable release contract validates the versioned contents instead.
php "$ROOT/scripts/generate-manifest.php" --check
(cd "$ROOT" && sha256sum -c MANIFEST.sha256 >/dev/null)
"$PYTHON_BIN" - "$ROOT/vazin-package.json" "$VERSION" <<'PY'
import json,sys
m=json.load(open(sys.argv[1],encoding='utf-8')); version=sys.argv[2]
assert set(m)=={'schema','product','type','version','minimum_php','entrypoint','upgrade_only','managed_site_upgrade_contract','supports_preview','supports_rollback','compatible_targets','minimum_vazin_online','minimum_current_version','supported_current_versions','release_channel','risk_level','connector_version','requires','release_notes'}
assert m['schema']==2 and m['product']=='VazinCMS' and m['type']=='vazincms' and m['version']==version=='10.30.0'
assert m['entrypoint']=='deploy/install.sh' and m['minimum_php']=='8.2'
assert m['upgrade_only'] is True and m['managed_site_upgrade_contract']=='external-runtime-v1'
assert m['minimum_vazin_online']=='16.8.27' and m['minimum_current_version']=='10.29.0'
assert m['supported_current_versions']==['10.29.0'] and m['connector_version']=='2.2.0'
assert m['release_channel']=='stable' and m['risk_level']=='high' and m['supports_rollback'] is True
assert m['requires']=={'vazin_id':'5.4.3','vazinpay':'21.4.1'}
PY
grep -Fq 'repairAuthentication' "$ROOT/src/SchemaHealth.php"
grep -Fq '/connector/v2/status' "$ROOT/src/App.php"
grep -Fq 'X_VAZIN_NONCE' "$ROOT/src/App.php"
grep -Fq 'SchemaHealth::repairAuthentication' "$ROOT/src/Controllers/AuthController.php"
grep -Fq 'VAZINPAY_GATEWAY_URL=https://api.pay.vazin.online' "$ROOT/.env.example"
grep -Fq 'VAZINPAY_API_KEY=' "$ROOT/.env.example"
grep -Fq 'VAZINPAY_API_URL=https://pay.vazin.online' "$ROOT/.env.example"
grep -Fq 'VAZINPAY_PROJECT_API_KEY=' "$ROOT/.env.example"
grep -Fq 'VAZIN_ID_URL=https://id.vazin.online' "$ROOT/.env.example"
grep -Fq 'VAZIN_ONLINE_URL=https://online.vazin.online' "$ROOT/.env.example"
grep -Fq '/visa(?:/intake)?$#' "$ROOT/extensions/modules/visa/bootstrap.php"
grep -Fq '(new ManualVisaCaseController())->intake($locale);' "$ROOT/src/Controllers/TravelOrderController.php"
grep -Fq 'payment_status' "$ROOT/src/Controllers/TravelOrderController.php"
grep -Fq "'/v1/invoices'" "$ROOT/src/Controllers/TravelOrderController.php"
grep -Fq 'validPaidInvoice' "$ROOT/src/Controllers/TravelOrderController.php"
! grep -Fq 'بسته‌های آماده فروش' "$ROOT/views/visa-catalog.php"
! grep -Fq 'صفحه فروش' "$ROOT/views/visa-cases.php"
grep -Fq 'final class SiteLocale' "$ROOT/src/SiteLocale.php"
grep -Fq 'final class SiteBrand' "$ROOT/src/SiteBrand.php"
grep -Fq "str_ends_with(\$host,'.ru')" "$ROOT/scripts/configure-site-profile.php"
! grep -Fq 'Powered by VazinCMS' "$ROOT/views/public/foot.php"
! grep -Fq 'اکوسیستم آنلاین وزین' "$ROOT/views/public/site-home.php"
grep -Fq 'PublicationService::processDue' "$ROOT/scripts/run-scheduler.php"
grep -Fq 'PublishingCrypto::encrypt' "$ROOT/src/Controllers/PublishingController.php"
! grep -Rqs 'social_destinations.*is_enabled=1' "$ROOT/src"
grep -Fq 'publication_jobs' "$ROOT/database/migrations/10.2.0-sqlite.sql"
grep -Fq "glob(\$root . '/database/migrations/*-'" "$ROOT/scripts/migrate.php"
grep -Fq 'SessionSecurity::boot()' "$ROOT/src/bootstrap.php"
grep -Fq "REVISION_CLAIM = 'https://vazin.online/claims/profile_revision'" "$ROOT/src/IdentityProfile.php"
grep -Fq "profile_revision=:profile_revision" "$ROOT/src/VazinIdentityLink.php"
grep -Fq " FOR UPDATE" "$ROOT/src/VazinIdentityLink.php"
grep -Fq "BEGIN IMMEDIATE" "$ROOT/src/DatabaseTransaction.php"
grep -Fq "profile_revision INTEGER" "$ROOT/database/migrations/10.6.2-sqlite.sql"
grep -Fq "profile_revision BIGINT" "$ROOT/database/migrations/10.6.2-pgsql.sql"
test -s "$ROOT/CHANGELOG-10.6.2-FA.md"
grep -Fq "CREATE TABLE cms_extensions" "$ROOT/database/migrations/10.7.0-sqlite.sql"
grep -Fq "extension-packages" "$ROOT/src/App.php"
grep -Fq "vazin-extension.json" "$ROOT/src/ExtensionManifest.php"
grep -Fq "admin_navigation" "$ROOT/src/ExtensionManifest.php"
grep -Fq "module-assets" "$ROOT/src/App.php"
test -s "$ROOT/extensions/themes/vazin-default/vazin-extension.json"
test -s "$ROOT/extensions/modules/travel/bootstrap.php"
test -s "$ROOT/scripts/build-release.php"
test -s "$ROOT/CHANGELOG-10.7.0-FA.md"
grep -Fq "CREATE TABLE IF NOT EXISTS telegram_connections" "$ROOT/database/migrations/10.8.0-sqlite.sql"
grep -Fq "CREATE TABLE IF NOT EXISTS identity_providers" "$ROOT/database/migrations/10.8.0-pgsql.sql"
grep -Fq "telegram-sync" "$ROOT/src/App.php"
grep -Fq "secret_token" "$ROOT/src/TelegramSyncService.php"
grep -Fq "initData" "$ROOT/src/TelegramWebAppAuth.php"
grep -Fq "content_advisories" "$ROOT/src/ContentAdvisoryService.php"
grep -Fq "published_at" "$ROOT/src/TelegramSyncService.php"
grep -Fq "'ru' => ['title'=>'Архив канала'" "$ROOT/src/Controllers/TelegramController.php"
grep -Fq "'en' => ['title'=>'Channel archive'" "$ROOT/src/Controllers/TelegramController.php"
grep -Fq "'/sitemap.xml'" "$ROOT/extensions/modules/seo/bootstrap.php"
grep -Fq "'/robots.txt'" "$ROOT/extensions/modules/seo/bootstrap.php"
test -s "$ROOT/extensions/modules/telegram/bootstrap.php"
test -s "$ROOT/extensions/modules/vazin-id/bootstrap.php"
test -s "$ROOT/extensions/modules/seo/bootstrap.php"
test -s "$ROOT/CHANGELOG-10.8.0-FA.md"
test -s "$ROOT/docs/TELEGRAM-FA.md"
grep -Fq "CREATE TABLE IF NOT EXISTS telegram_assistant_profiles" "$ROOT/database/migrations/10.9.0-sqlite.sql"
grep -Fq "CREATE TABLE IF NOT EXISTS telegram_assistant_profiles" "$ROOT/database/migrations/10.9.0-pgsql.sql"
grep -Fq "CREATE TABLE IF NOT EXISTS telegram_appointment_reservations" "$ROOT/database/migrations/10.9.0-sqlite.sql"
grep -Fq "CREATE TABLE IF NOT EXISTS telegram_assistant_outbox" "$ROOT/database/migrations/10.9.0-pgsql.sql"
grep -Fq "contact_id INTEGER REFERENCES telegram_assistant_contacts" "$ROOT/database/migrations/10.9.0-sqlite.sql"
grep -Fq "contact_id BIGINT REFERENCES telegram_assistant_contacts" "$ROOT/database/migrations/10.9.0-pgsql.sql"
grep -Fq "telegram-business-assistant" "$ROOT/src/App.php"
grep -Fq "final class TelegramBusinessService" "$ROOT/src/TelegramBusinessService.php"
grep -Fq "final class TelegramAssistantService" "$ROOT/src/TelegramAssistantService.php"
grep -Fq "final class TelegramMiniAppSession" "$ROOT/src/TelegramMiniAppSession.php"
grep -Fq "final class AppointmentService" "$ROOT/src/AppointmentService.php"
grep -Fq "final class TelegramAssistantController" "$ROOT/src/Controllers/TelegramAssistantController.php"
grep -Fq "/telegram/assistant-preview/" "$ROOT/extensions/modules/telegram/bootstrap.php"
grep -Fq "TelegramAssistantWorker::process" "$ROOT/extensions/modules/telegram/bootstrap.php"
grep -Fq "TelegramAssistantWorker::process" "$ROOT/scripts/run-telegram-assistant.php"
grep -Fq "TelegramAssistantMaintenance::run" "$ROOT/scripts/run-telegram-assistant.php"
grep -Fq 'scripts/extensions.php" sync' "$ROOT/deploy/install.sh"
grep -Fq "https://telegram.org/js/telegram-web-app.js?63" "$ROOT/views/telegram-assistant.php"
grep -Fq "credentials:state.mode === 'admin' ? 'same-origin' : 'omit'" "$ROOT/public/assets/telegram-assistant-1090.js"
grep -Fq "TELEGRAM_BUSINESS_ENABLED=false" "$ROOT/.env.example"
grep -Fq "TELEGRAM_ASSISTANT_DELIVERY_ENABLED=false" "$ROOT/.env.example"
grep -Fq "TELEGRAM_ASSISTANT_AUTOREPLY_ENABLED=false" "$ROOT/.env.example"
grep -Fq "TELEGRAM_ASSISTANT_PREVIEW_ENABLED=false" "$ROOT/.env.example"
test -s "$ROOT/CHANGELOG-10.9.0-FA.md"
test -s "$ROOT/CHANGELOG-10.9.1-FA.md"
test -s "$ROOT/CHANGELOG-10.9.2-FA.md"
grep -Fq 'http_response_code($ok?200:503)' "$ROOT/src/App.php"
grep -Fq 'min(10, $batchSize)' "$ROOT/scripts/run-telegram-assistant.php"
grep -Fq "VALUES('10.9.1')" "$ROOT/database/migrations/10.9.1-sqlite.sql"
grep -Fq "VALUES('10.9.1')" "$ROOT/database/migrations/10.9.1-pgsql.sql"
grep -Fq "VALUES('10.9.2')" "$ROOT/database/migrations/10.9.2-sqlite.sql"
grep -Fq "VALUES('10.9.2')" "$ROOT/database/migrations/10.9.2-pgsql.sql"
grep -Fq "VALUES('10.10.0')" "$ROOT/database/migrations/10.10.0-sqlite.sql"
grep -Fq "VALUES('10.10.0')" "$ROOT/database/migrations/10.10.0-pgsql.sql"
grep -Fq "VALUES('10.10.1')" "$ROOT/database/migrations/10.10.1-sqlite.sql"
grep -Fq "VALUES('10.10.1')" "$ROOT/database/migrations/10.10.1-pgsql.sql"
grep -Fq "VALUES('10.10.2')" "$ROOT/database/migrations/10.10.2-sqlite.sql"
grep -Fq "VALUES('10.10.2')" "$ROOT/database/migrations/10.10.2-pgsql.sql"
grep -Fq "VALUES('10.10.3')" "$ROOT/database/migrations/10.10.3-sqlite.sql"
grep -Fq "VALUES('10.10.3')" "$ROOT/database/migrations/10.10.3-pgsql.sql"
grep -Fq "VALUES('10.10.4')" "$ROOT/database/migrations/10.10.4-sqlite.sql"
grep -Fq "VALUES('10.10.4')" "$ROOT/database/migrations/10.10.4-pgsql.sql"
grep -Fq "VALUES('10.10.5')" "$ROOT/database/migrations/10.10.5-sqlite.sql"
grep -Fq "VALUES('10.10.5')" "$ROOT/database/migrations/10.10.5-pgsql.sql"
grep -Fq "VALUES('10.10.6')" "$ROOT/database/migrations/10.10.6-sqlite.sql"
grep -Fq "VALUES('10.10.6')" "$ROOT/database/migrations/10.10.6-pgsql.sql"
grep -Fq "VALUES('10.10.7')" "$ROOT/database/migrations/10.10.7-sqlite.sql"
grep -Fq "VALUES('10.10.7')" "$ROOT/database/migrations/10.10.7-pgsql.sql"
grep -Fq "VALUES('10.10.8')" "$ROOT/database/migrations/10.10.8-sqlite.sql"
grep -Fq "VALUES('10.10.8')" "$ROOT/database/migrations/10.10.8-pgsql.sql"
grep -Fq "VALUES('10.27.0')" "$ROOT/database/migrations/10.27.0-sqlite.sql"
grep -Fq "VALUES('10.28.0')" "$ROOT/database/migrations/10.28.0-sqlite.sql"
grep -Fq "VALUES('10.29.0')" "$ROOT/database/migrations/10.29.0-sqlite.sql"
grep -Fq "VALUES('10.27.0')" "$ROOT/database/migrations/10.27.0-pgsql.sql"
grep -Fq "VALUES('10.28.0')" "$ROOT/database/migrations/10.28.0-pgsql.sql"
grep -Fq "VALUES('10.29.0')" "$ROOT/database/migrations/10.29.0-pgsql.sql"
grep -Fq 'visa_application_intakes' "$ROOT/database/migrations/10.10.0-sqlite.sql"
grep -Fq 'travel_provider_connections' "$ROOT/database/migrations/10.10.0-pgsql.sql"
grep -Fq 'telegram_alert_subscriptions' "$ROOT/database/migrations/10.10.0-sqlite.sql"
grep -Fq 'TELEGRAM_ALERT_DELIVERY_ENABLED=false' "$ROOT/.env.example"
grep -Fq 'final class TravelAlertService' "$ROOT/src/TravelAlertService.php"
grep -Fq 'final class TravelAlertWorker' "$ROOT/src/TravelAlertWorker.php"
grep -Fq 'TravelAlertWorker::process' "$ROOT/extensions/modules/telegram/bootstrap.php"
grep -Fq 'VisaApplicationController' "$ROOT/extensions/modules/visa/bootstrap.php"
test -s "$ROOT/public/qa/ui/travel-platform-fa.html"
test -s "$ROOT/public/qa/ui/visa-platform-fa.html"
test -s "$ROOT/CHANGELOG-10.10.0-FA.md"
test -s "$ROOT/CHANGELOG-10.10.1-FA.md"
test -s "$ROOT/CHANGELOG-10.10.2-FA.md"
test -s "$ROOT/CHANGELOG-10.10.3-FA.md"
test -s "$ROOT/CHANGELOG-10.10.4-FA.md"
test -s "$ROOT/CHANGELOG-10.10.5-FA.md"
test -s "$ROOT/CHANGELOG-10.10.6-FA.md"
test -s "$ROOT/CHANGELOG-10.10.7-FA.md"
test -s "$ROOT/CHANGELOG-10.10.8-FA.md"
test -s "$ROOT/CHANGELOG-10.27.0-FA.md"
test -s "$ROOT/CHANGELOG-10.28.0-FA.md"
test -s "$ROOT/CHANGELOG-10.29.0-FA.md"
test -s "$ROOT/CHANGELOG-10.30.0-FA.md"
test -s "$ROOT/database/migrations/10.30.0-sqlite.sql"
test -s "$ROOT/database/migrations/10.30.0-pgsql.sql"
test -s "$ROOT/tests/managed-site-external-upgrade-contract.php"
test -s "$ROOT/scripts/tenant-demo-preflight.php"
test -s "$ROOT/docs/tenant-demo.example.json"
test -s "$ROOT/tests/tenant-demo-preflight-contract.php"
test -s "$ROOT/tests/admin-brand-locale-contract.php"
test -s "$ROOT/tests/admin-brand-locale-render-contract.php"
test -s "$ROOT/tests/admin-navigation-contract.php"
test -s "$ROOT/tests/manual-visa-no-checkout-contract.php"
grep -Fq "NEW_VERSION='10.30.0'" "$ROOT/deploy/install.sh"
grep -Fq "OLD_VERSION='10.29.0'" "$ROOT/deploy/install.sh"
grep -Fq 'VAZIN_VISA_DIRECT_SALES_ENABLED=false' "$ROOT/.env.example"
grep -Fq 'ManualVisaCaseController' "$ROOT/extensions/modules/visa/bootstrap.php"
grep -Fq 'function forOperator' "$ROOT/src/VisaApplicationService.php"
grep -Fq 'external-runtime-v1' "$ROOT/vazin-package.json"
grep -Fq 'existing external runtime bindings are not exact before code swap' "$ROOT/deploy/atomic_release.py"
! test -e "$ROOT/deploy/bootstrap-install.sh"
! test -e "$ROOT/tests/managed-site-bootstrap-contract.php"
grep -Fq "channel<>'admin'" "$ROOT/src/Scheduler.php"
grep -Fq 'generateSlotsForProfile' "$ROOT/src/Controllers/TelegramAssistantController.php"
grep -Fq 'budget_exhausted' "$ROOT/src/TelegramAssistantWorker.php"
test -s "$ROOT/tests/telegram-appointment-scheduling-contract.php"
test -s "$ROOT/docs/TELEGRAM-ASSISTANT-FA.md"
! grep -Fq '/var/www/vazin-sites/itgala-ru' "$ROOT/deploy/install.sh"
! grep -Fq '/var/www/vazin-sites/itgala-ru' "$ROOT/deploy/rollback.sh"
! grep -Rqs 'namespace VazinOnline' "$ROOT/src"
! grep -Fq "getenv('VAZIN_ID_URL')?:''),'/');\$apiKey" "$ROOT/src/Controllers/TravelOrderController.php"
for script in "$ROOT/deploy/install.sh" "$ROOT/deploy/rollback.sh" "$ROOT/deploy/provision.sh"; do bash -n "$script"; done
if command -v node >/dev/null; then node --check "$ROOT/public/assets/telegram-assistant-1090.js"; fi
"$PYTHON_BIN" -m unittest discover -s "$ROOT/tests" -p 'test_*.py' -v
if command -v php >/dev/null; then
  find "$ROOT" -type f -name '*.php' -print0 | xargs -0 -n1 php -l >/dev/null
  php "$ROOT/tests/identity-link-contract.php"
  php "$ROOT/tests/admin-brand-locale-contract.php"
  php "$ROOT/tests/admin-brand-locale-render-contract.php"
  php "$ROOT/tests/admin-navigation-contract.php"
  php "$ROOT/tests/travel-alerts-responsive-contract.php"
  php "$ROOT/tests/local-return-contract.php"
  php "$ROOT/tests/extension-kernel.php"
  php "$ROOT/tests/update-feed-contract.php"
  php "$ROOT/tests/delivery-policy-contract.php"
  php "$ROOT/tests/telegram-assistant-security-contract.php"
  php "$ROOT/tests/telegram-business-authorization-contract.php"
  php "$ROOT/tests/telegram-assistant-contract.php"
  php "$ROOT/tests/telegram-appointment-scheduling-contract.php"
  php "$ROOT/tests/travel-visa-platform-contract.php"
  php "$ROOT/tests/travel-visa-commerce-contract.php"
  php "$ROOT/tests/vazinpay-gateway-contract.php"
  php "$ROOT/tests/travel-visa-vazinpay-adapter-contract.php"
  php "$ROOT/tests/travel-visa-activation-gate-contract.php"
  php "$ROOT/tests/travel-visa-webhook-endpoint-contract.php"
  php "$ROOT/tests/manual-visa-no-checkout-contract.php"
  php "$ROOT/tests/agency-request-render-contract.php"
  php "$ROOT/tests/agency-inquiry-workflow-contract.php"
  php "$ROOT/tests/telegram-alert-readiness-contract.php"
  php "$ROOT/tests/tenant-demo-preflight-contract.php"
  php "$ROOT/tests/travel-footer-contrast-contract.php"
  php "$ROOT/tests/public-theme-ui-contract.php"
  php "$ROOT/tests/managed-site-external-upgrade-contract.php"
  php "$ROOT/tests/health-contract.php"
  php "$ROOT/tests/stage4-contract.php"
  php "$ROOT/tests/smoke.php"
else
  echo 'PHP CLI unavailable; server installer will run lint and PHP contracts.'
fi
echo "VazinCMS $VERSION release check passed."
