<?php use VazinCMS\Security;$directSalesEnabled=(bool)($directSalesEnabled??false);$statusLabels=['new'=>'جدید','awaiting_payment'=>'منتظر پرداخت','paid'=>'پرداخت‌شده','reviewing'=>'در حال بررسی','documents_required'=>'نیازمند مدرک','processing'=>'در حال انجام','completed'=>'تکمیل‌شده','rejected'=>'ردشده','cancelled'=>'لغوشده','accepted'=>'تأییدشده','not_required'=>'بدون پرداخت آنلاین'];$docLabels=['passport'=>'گذرنامه','photo'=>'عکس پرسنلی','insurance'=>'بیمه مسافرتی','invitation'=>'دعوت‌نامه','education'=>'مدارک تحصیلی','financial'=>'مدارک مالی','booking'=>'رزرو سفر','other'=>'سایر مدارک'];?>
<section class="case-portal"><header><span class="status-chip">پرونده <?=Security::e($order['public_id'])?></span><h1>پیگیری پرونده ویزا</h1><p><?=Security::e($order['full_name'])?>، وضعیت و مدارک پرونده شما در این صفحه نگهداری می‌شود.</p></header>
<?php if(isset($_GET['created'])):?><div class="visa-alert success"><b><?=$directSalesEnabled?'سفارش با موفقیت ثبت شد.':'پروندهٔ دستی eVisa با موفقیت باز شد.'?></b><br>کد محرمانه پیگیری: <strong><?=Security::e($accessCode)?></strong><br><small><?=$directSalesEnabled?'این کد را ذخیره کنید؛ برای ورود دوباره به پرونده لازم است.':'این کد سفارش یا فاکتور نیست؛ فقط برای ورود دوباره به پروندهٔ محافظت‌شده لازم است.'?></small></div><?php endif;?>
<?php if($directSalesEnabled&&isset($_GET['payment'])&&$order['payment_status']==='paid'):?><div class="visa-alert success">پرداخت VazinPay تأیید شد و پرونده وارد صف بررسی گردید.</div><?php endif;?>
<?php if(isset($_GET['uploaded'])):?><div class="visa-alert success">مدرک با موفقیت و به‌صورت امن بارگذاری شد.</div><?php endif;?><?php if($uploadError):?><div class="visa-alert error"><?=Security::e($uploadError)?></div><?php endif;?>
<div class="case-overview"><article><span>خدمت</span><strong><?=Security::e((string)($order['product_title']??$order['service_type']))?></strong></article><article><span>وضعیت پرونده</span><strong><?=Security::e($statusLabels[$order['status']]??$order['status'])?></strong></article><?php if($directSalesEnabled):?><article><span>مبلغ</span><strong><?=number_format((float)$order['amount'],0)?> <?=Security::e($order['currency'])?></strong></article><article><span>پرداخت</span><strong><?=$order['payment_status']==='paid'?'پرداخت‌شده':'پرداخت‌نشده'?></strong></article><?php else:?><article><span>مدل انجام</span><strong>بررسی دستی آژانس</strong></article><article><span>پرداخت آنلاین</span><strong>غیرفعال</strong></article><?php endif;?></div>
<?php if($directSalesEnabled&&$payUrl):?><a class="case-pay" rel="nofollow" href="<?=Security::e($payUrl)?>">پرداخت امن با VazinPay <span>←</span></a><?php elseif($directSalesEnabled&&$order['payment_status']!=='paid'&&$payError):?><div class="visa-alert error"><?=Security::e($payError)?></div><?php endif;?>
<?php if(($order['service_type']??'')==='visa'):?><a class="case-pay" href="/<?=Security::e($locale)?>/order/<?=Security::e($order['public_id'])?>/application">تکمیل فرم امن eVisa <span aria-hidden="true">←</span></a><?php endif;?>
<?php if(($alertOptIn['status']??'')==='pending'&&!empty($alertOptIn['url'])):?><a class="case-pay" href="<?=Security::e((string)$alertOptIn['url'])?>" target="_blank" rel="noopener noreferrer">فعال‌سازی اختیاری هشدار Telegram <span aria-hidden="true">←</span></a><p class="muted">پس از Start کردن ربات، فقط تغییر وضعیت پرونده برای شما ارسال می‌شود؛ هیچ مدرک یا اطلاعات گذرنامه‌ای در Telegram ارسال نمی‌شود.</p><?php elseif(($alertOptIn['status']??'')==='opted_in'):?><div class="visa-alert success">هشدارهای اختیاری Telegram برای این پرونده فعال است. برای لغو، /stop را در همان ربات ارسال کنید.</div><?php endif;?>
<div class="case-columns"><section class="case-card"><h2>بارگذاری امن مدارک</h2><p>فایل‌ها مستقیماً در فضای خصوصی پرونده ذخیره می‌شوند و لینک عمومی ندارند.</p><form class="case-upload" method="post" action="/<?=Security::e($locale)?>/order/<?=Security::e($order['public_id'])?>/documents" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><label>نوع مدرک<select name="document_type"><?php foreach($docLabels as$v=>$l):?><option value="<?=$v?>"><?=$l?></option><?php endforeach;?></select></label><label>انتخاب فایل<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png,.webp" required></label><small>PDF، JPG، PNG یا WEBP — حداکثر ۱۵ مگابایت</small><button>بارگذاری مدرک</button></form><div class="customer-documents"><?php foreach($caseDocuments as$d):?><a href="/visa-document/<?=(int)$d['id']?>/download"><span><?=Security::e($docLabels[$d['document_type']]??$d['document_type'])?><small><?=Security::e($d['original_name'])?></small></span><b class="doc-<?=Security::e($d['status'])?>"><?=$d['status']==='accepted'?'تأییدشده':($d['status']==='rejected'?'نیازمند اصلاح':'در انتظار بررسی')?></b></a><?php endforeach;?><?php if(!$caseDocuments):?><p class="muted">هنوز مدرکی بارگذاری نشده است.</p><?php endif;?></div></section>
<section class="case-card"><h2>خط زمانی پرونده</h2><div class="customer-timeline"><?php foreach($caseEvents as$e):?><article><i></i><div><time><?=Security::e((string)$e['created_at'])?></time><strong><?=$e['new_status']?Security::e($statusLabels[$e['new_status']]??$e['new_status']):'به‌روزرسانی پرونده'?></strong><?php if($e['display_message']):?><p><?=nl2br(Security::e((string)$e['display_message']))?></p><?php endif;?></div></article><?php endforeach;?><?php if(!$caseEvents):?><article><i></i><div><strong>پرونده ثبت شده است</strong><p><?=$directSalesEnabled?'پس از پرداخت یا بررسی مدیر، به‌روزرسانی‌ها اینجا نمایش داده می‌شود.':'پس از بررسی دستی آژانس، به‌روزرسانی‌ها اینجا نمایش داده می‌شود.'?></p></div></article><?php endif;?></div></section></div></section>
