<?php use VazinCMS\Security; ?>
<section class="visa-checkout"><div class="section-title"><span>ثبت سفارش امن</span><h1>شروع پرونده ویزا و مهاجرت</h1><p>بسته را انتخاب کنید؛ مبلغ فقط از فهرست رسمی سرور خوانده می‌شود.</p></div>
<?php if($errors):?><div class="visa-alert error"><?php foreach($errors as $error):?><div><?=Security::e($error)?></div><?php endforeach;?></div><?php endif;?>
<?php if(!$products):?><div class="visa-alert">هنوز بسته فروشی فعال نشده است. با پشتیبانی تماس بگیرید.</div><?php else:?><form method="post" class="travel-form visa-order-form"><input type="hidden" name="_csrf" value="<?=Security::e(Security::csrf())?>"><input type="hidden" name="service_type" value="visa">
<fieldset class="wide"><legend>انتخاب خدمت</legend><label class="wide">بسته خدمت<select name="product_code" required><?php foreach($products as $p):?><option value="<?=Security::e($p['code'])?>" <?=$selected===$p['code']?'selected':''?>><?=Security::e($p['title'])?> — <?=number_format((float)$p['price'],0)?> <?=Security::e($p['currency'])?></option><?php endforeach;?></select><small>مبلغ نهایی از فهرست رسمی سرور دریافت می‌شود.</small></label></fieldset>
<fieldset><legend>اطلاعات متقاضی</legend><div class="form-grid"><label>نام و نام خانوادگی<input name="full_name" maxlength="190" required autocomplete="name"></label><label>شماره تماس<input name="phone" maxlength="64" required autocomplete="tel" inputmode="tel"></label><label>ایمیل <small>اختیاری</small><input type="email" name="email" maxlength="190" autocomplete="email" inputmode="email"></label><label>ملیت<input name="nationality" maxlength="100" value="ایران"></label></div></fieldset>
<fieldset><legend>اطلاعات سفر</legend><div class="form-grid"><label>مقصد<input name="destination" maxlength="190" value="روسیه"></label><label>تعداد متقاضی<input type="number" name="travelers" min="1" max="50" value="1"></label><label class="wide">تاریخ تقریبی سفر <small>اختیاری</small><input type="date" name="travel_date"></label></div></fieldset>
<fieldset class="wide"><legend>توضیحات پرونده</legend><label class="wide">شرح وضعیت پرونده<textarea name="notes" maxlength="3000" rows="5" placeholder="نوع ویزا، هدف سفر و نکات مهم را بنویسید"></textarea></label></fieldset>
<div class="checkout-actions wide"><label class="consent"><input type="checkbox" required><span>اطلاعات واردشده صحیح است و با بررسی پرونده موافقم.</span></label><button class="primary" type="submit">ثبت سفارش و ادامه به پرداخت <span aria-hidden="true">←</span></button><small>در مرحله بعد، فاکتور امن VazinPay ساخته می‌شود.</small></div></form><?php endif;?></section>
