<?php
use VazinCMS\{Security,SiteLocale};
$copy=SiteLocale::text($locale);
$decode=static function(string $key,array $fallback)use($settings,$locale):array{$localized=$key.'.'.$locale;$value=json_decode((string)($settings[$localized]??$settings[$key]??''),true);return is_array($value)&&$value?$value:$fallback;};
$pick=static function(string $key,string $fallback)use($settings,$locale):string{$localized=trim((string)($settings[$key.'.'.$locale]??''));if($localized!=='')return$localized;$global=trim((string)($settings[$key]??''));return$global!==''?$global:$fallback;};
$features=$decode('features_json',$copy['features']);$steps=$decode('steps_json',$copy['steps']);$stats=$decode('stats_json',$copy['stats']);$faqs=$decode('faq_json',$copy['faq']);
$title=$pick('hero_title',$copy['title']);$text=$pick('hero_text',$copy['text']);$badge=$pick('hero_badge',$copy['badge']);
$primaryUrl=$pick('primary_cta_url','/'.$locale.'/page/contact');$secondaryUrl=$pick('secondary_cta_url','/'.$locale.'/page/about');
$mark=mb_strtoupper(mb_substr(preg_replace('/[^\p{L}\p{N}]+/u','',$siteName),0,2));
?>
<section class="vz-hero"><div class="hero-copy"><span class="vz-badge"><?=Security::e($badge)?></span><h1><?=Security::e($title)?></h1><p><?=Security::e($text)?></p><div class="hero-actions"><a class="primary" href="<?=Security::e($primaryUrl)?>"><?=Security::e($pick('primary_cta_label',$copy['start']))?></a><a class="secondary" href="<?=Security::e($secondaryUrl)?>"><?=Security::e($pick('secondary_cta_label',$copy['more']))?></a></div></div><div class="hero-visual" aria-hidden="true"><span><?=Security::e($mark?:mb_substr($siteName,0,1))?></span><i></i><i></i><i></i></div></section>
<section class="vz-stats"><?php foreach($stats as $item):?><article><strong><?=Security::e((string)($item[0]??''))?></strong><span><?=Security::e((string)($item[1]??''))?></span></article><?php endforeach;?></section>
<section class="vz-section"><div class="section-heading"><span><?=Security::e($copy['features_label'])?></span><h2><?=Security::e($copy['features_title'])?></h2></div><div class="feature-grid"><?php foreach($features as $index=>$item):?><article><b><?=str_pad((string)($index+1),2,'0',STR_PAD_LEFT)?></b><h3><?=Security::e((string)($item[0]??''))?></h3><p><?=Security::e((string)($item[1]??''))?></p></article><?php endforeach;?></div></section>
<section class="vz-section steps"><div class="section-heading"><span><?=Security::e($copy['steps_label'])?></span><h2><?=Security::e($copy['steps_title'])?></h2></div><div class="steps-grid"><?php foreach($steps as $index=>$item):?><article><em><?=$index+1?></em><div><h3><?=Security::e((string)($item[0]??''))?></h3><p><?=Security::e((string)($item[1]??''))?></p></div></article><?php endforeach;?></div></section>
<?php if(!empty($page['body'])):?><section class="vz-section content-section"><div class="section-heading"><span><?=Security::e($copy['about'])?></span><h2><?=Security::e($page['title']??$siteName)?></h2></div><div class="rich-content"><?=nl2br(Security::e($page['body']))?></div></section><?php endif;?>
<section class="vz-section faq"><div class="section-heading"><span><?=Security::e($copy['faq_label'])?></span><h2><?=Security::e($copy['faq_title'])?></h2></div><div class="faq-list"><?php foreach($faqs as $item):?><details><summary><?=Security::e((string)($item[0]??''))?></summary><p><?=Security::e((string)($item[1]??''))?></p></details><?php endforeach;?></div></section>
<section class="final-cta"><div><h2><?=Security::e($pick('site_tagline',$copy['ready']))?></h2><p><?=Security::e($pick('site_description',$copy['ready_text']))?></p></div><a href="<?=Security::e($primaryUrl)?>"><?=Security::e($pick('primary_cta_label',$copy['start']))?></a></section>
<script nonce="<?=Security::e(Security::cspNonce())?>" type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Organization','name'=>$siteName,'description'=>$settings['site_description.'.$locale]??$settings['site_description']??$text,'url'=>($_SERVER['REQUEST_SCHEME']??'https').'://'.($_SERVER['HTTP_HOST']??'')],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
