<?php
use VazinCMS\Security;

$ru=$locale==='ru';
$en=$locale==='en';
$copy=$ru?[
  'eyebrow'=>'WHITE-LABEL VISA PLATFORM','title'=>'Визовые дела под брендом агентства — с человеческой проверкой там, где она нужна.','text'=>'Vazin Visa — это не обещание автоматической выдачи. Это безопасный процесс: умная анкета, документы, чек-лист, статусы, оператор и добровольные уведомления.','primary'=>'Начать визовую анкету','secondary'=>'Проверить требования','features'=>[['Полная анкета','Паспортные, контактные, поездочные и рабочие данные собираются в защищённом процессе.'],['Ручная работа видна','Оператор проверяет, просит исправления и фиксирует этапы; API включается только при договоре.'],['Дела и документы','Заявитель загружает документы, видит статус и получает только безопасные уведомления.']], 'ctaTitle'=>'Сделайте визовый процесс понятным для агентства и заявителя.','ctaText'=>'Каждый tenant хранит бренд, процесс, документы и Telegram-подписки отдельно.','cta'=>'Открыть анкету',
]:($en?[
  'eyebrow'=>'WHITE-LABEL VISA PLATFORM','title'=>'Visa cases under the agency brand, with human review where it belongs.','text'=>'Vazin Visa never promises automatic issuance. It provides a secure workflow: a complete application, documents, checklist, status timeline, operator review and opt-in alerts.','primary'=>'Start a visa application','secondary'=>'Check visa requirements','features'=>[['Complete intake','Passport, contact, travel and employment data are collected in a protected workflow.'],['Visible manual work','An operator reviews, requests corrections and records milestones; an API is enabled only where contracted.'],['Cases and documents','Applicants upload documents, see status and receive only safe notifications.']], 'ctaTitle'=>'Make the visa journey clear for the agency and the applicant.','ctaText'=>'Every tenant keeps its brand, process, documents and Telegram preferences isolated.','cta'=>'Open application',
]:[
  'eyebrow'=>'پلتفرم وایت‌لیبل ویزا','title'=>'پرونده‌های ویزا با برند آژانس؛ با بررسی انسانی در جایی که لازم است.','text'=>'Vazin Visa وعدهٔ صدور خودکار نمی‌دهد. یک فرایند امن می‌دهد: فرم کامل، مدارک، چک‌لیست، وضعیت پرونده، بررسی کارشناس و هشدارهای اختیاری.','primary'=>'شروع فرم ویزا','secondary'=>'بررسی شرایط ویزا','features'=>[['فرم کامل','اطلاعات پاسپورت، تماس، سفر و شغل در یک فرایند محافظت‌شده دریافت می‌شود.'],['کار دستی شفاف','کارشناس بررسی می‌کند، رفع نقص می‌خواهد و مراحل را ثبت می‌کند؛ API فقط با قرارداد فعال می‌شود.'],['پرونده و مدارک','متقاضی مدارک را آپلود می‌کند، وضعیت را می‌بیند و فقط هشدار امن دریافت می‌کند.']], 'ctaTitle'=>'فرایند ویزا را برای آژانس و متقاضی قابل‌فهم کنید.','ctaText'=>'برند، فرایند، مدارک و ترجیح تلگرام هر tenant کاملاً جدا می‌ماند.','cta'=>'باز کردن فرم',
]);
?>
<div class="platform-shell">
  <section class="platform-hero">
    <div><span class="platform-eyebrow"><?=Security::e($copy['eyebrow'])?></span><h1><?=Security::e($copy['title'])?></h1><p><?=Security::e($copy['text'])?></p><div class="platform-actions"><a class="primary" href="/<?=Security::e($locale)?>/visa"><?=Security::e($copy['primary'])?></a><a href="/<?=Security::e($locale)?>/visa-selector"><?=Security::e($copy['secondary'])?></a></div></div>
    <aside class="platform-console"><div class="console-head"><strong><?=Security::e($ru?'Визовое дело':($en?'Visa case':'پروندهٔ ویزا'))?></strong><span class="platform-status"><?=Security::e($ru?'ручная проверка':($en?'manual review':'بررسی انسانی'))?></span></div><div class="console-row"><span><?=Security::e($ru?'Анкета':($en?'Application':'فرم'))?></span><b><?=Security::e($ru?'защищена':($en?'protected':'محافظت‌شده'))?></b></div><div class="console-row"><span><?=Security::e($ru?'Документы':($en?'Documents':'مدارک'))?></span><b><?=Security::e($ru?'частный доступ':($en?'private access':'دسترسی خصوصی'))?></b></div><div class="console-row"><span>Telegram</span><b><?=Security::e($ru?'по согласию':($en?'opt-in':'اختیاری'))?></b></div></aside>
  </section>
  <section class="platform-section"><span class="platform-kicker">01</span><h2><?=Security::e($ru?'Надёжный процесс вместо неподтверждённых обещаний':($en?'A reliable process instead of unverified promises':'فرایند قابل‌اعتماد به‌جای وعده‌های تأییدنشده'))?></h2><div class="platform-grid"><?php foreach($copy['features'] as $item):?><article class="platform-card"><h3><?=Security::e($item[0])?></h3><p><?=Security::e($item[1])?></p></article><?php endforeach;?></div></section>
  <section class="platform-section"><span class="platform-kicker">02</span><h2><?=Security::e($ru?'Четыре ясных этапа':($en?'Four clear stages':'چهار مرحلهٔ روشن'))?></h2><div class="platform-timeline"><article class="platform-timeline-item"><b>01</b><h3><?=Security::e($ru?'Выбор':($en?'Select':'انتخاب'))?></h3><p><?=Security::e($ru?'Гражданство, цель, страна и тип визы.':($en?'Nationality, purpose, destination and visa type.':'ملیت، هدف، مقصد و نوع ویزا.'))?></p></article><article class="platform-timeline-item"><b>02</b><h3><?=Security::e($ru?'Анкета':($en?'Application':'فرم'))?></h3><p><?=Security::e($ru?'Версионированные обязательные поля и согласие.':($en?'Versioned required fields and consent.':'فیلدهای الزامی نسخه‌دار و رضایت.'))?></p></article><article class="platform-timeline-item"><b>03</b><h3><?=Security::e($ru?'Проверка':($en?'Review':'بررسی'))?></h3><p><?=Security::e($ru?'Специалист и чек-лист, запрос исправления при необходимости.':($en?'Operator review and checklist, with correction requests when needed.':'کارشناس و چک‌لیست، با درخواست رفع نقص در صورت نیاز.'))?></p></article><article class="platform-timeline-item"><b>04</b><h3><?=Security::e($ru?'Отслеживание':($en?'Track':'پیگیری'))?></h3><p><?=Security::e($ru?'Безопасный статус, документы и добровольные Telegram-уведомления.':($en?'Secure status, documents and optional Telegram alerts.':'وضعیت امن، مدارک و هشدار اختیاری تلگرام.'))?></p></article></div></section>
  <section class="platform-callout"><div><h2><?=Security::e($copy['ctaTitle'])?></h2><p><?=Security::e($copy['ctaText'])?></p></div><a class="platform-button" href="/<?=Security::e($locale)?>/visa"><?=Security::e($copy['cta'])?></a></section>
</div>
<?php require __DIR__.'/foot.php'; ?>
