<?php
declare(strict_types=1);
namespace VazinCMS;
use InvalidArgumentException;
final class ModuleRegistry
{
 public const TYPES=['cms','payment','bot','hosting','service'];
 public const STATUSES=['planned','connecting','healthy','degraded','disabled'];
 public const CAPABILITIES=['content','travel','visa','localization','seo','payments','customers','orders','notifications','automation'];
 public static function all():array{return Database::connection()->query('SELECT * FROM module_instances ORDER BY name,id')->fetchAll();}
 public static function save(array $input,int $userId):int{$pdo=Database::connection();$id=(int)($input['id']??0);$key=strtolower(trim((string)($input['module_key']??'')));$name=trim((string)($input['name']??''));$type=(string)($input['module_type']??'service');$url=rtrim(trim((string)($input['base_url']??'')),'/');$status=(string)($input['status']??'planned');$caps=array_values(array_intersect((array)($input['capabilities']??[]),self::CAPABILITIES));if(!preg_match('/^[a-z0-9][a-z0-9-]{2,79}$/',$key)||mb_strlen($name)<3||!in_array($type,self::TYPES,true)||!in_array($status,self::STATUSES,true))throw new InvalidArgumentException('اطلاعات ماژول معتبر نیست.');if($url!==''&&(!filter_var($url,FILTER_VALIDATE_URL)||!str_starts_with($url,'https://')))throw new InvalidArgumentException('آدرس ماژول باید HTTPS معتبر باشد.');$data=['key'=>$key,'name'=>$name,'type'=>$type,'url'=>$url?:null,'status'=>$status,'caps'=>json_encode($caps,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'uid'=>$userId];if($id>0){$data['id']=$id;$pdo->prepare('UPDATE module_instances SET module_key=:key,name=:name,module_type=:type,base_url=:url,status=:status,capabilities=:caps,updated_at=CURRENT_TIMESTAMP WHERE id=:id')->execute($data);return $id;}$pdo->prepare('INSERT INTO module_instances(module_key,name,module_type,base_url,status,capabilities,created_by) VALUES(:key,:name,:type,:url,:status,:caps,:uid)')->execute($data);return(int)$pdo->lastInsertId();}
 public static function heartbeat(string $key,array $payload):array{$version=substr(trim((string)($payload['version']??'')),0,40);$status=(string)($payload['status']??'healthy');$error=trim((string)($payload['error']??''));if($version===''||!in_array($status,['healthy','degraded'],true))throw new InvalidArgumentException('گزارش سلامت ماژول معتبر نیست.');$s=Database::connection()->prepare('UPDATE module_instances SET version=:version,status=:status,last_error=:error,last_seen_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE module_key=:key');$s->execute(['version'=>$version,'status'=>$status,'error'=>$error?:null,'key'=>$key]);if($s->rowCount()!==1)throw new InvalidArgumentException('ماژول ثبت نشده است.');return['module_key'=>$key,'accepted'=>true,'server_time'=>gmdate('c')];}
}
